@startuml

skinparam sequenceMessageAlign center
title TO VIEW THE SPRINT BACKLOG OF SPRINT
legend top
US036 - As a PO/SM/Team Member, I want to consult the Sprint Backlog of a chosen sprint in the web UI.
end legend

class "SprintWebController"{
createSprintService
userStoriesInSprintService
+ getSprintBacklog(sprintId)
}

class UserStoriesInSprintService{
- sprintRepository
- userStoryRepository
- extractUsIds(userStoriesInSprint)
+ getSprintBacklog(sprintId)
}

class UserStoryMapper{
+ userStoryToDtoList(userStories)
}

class UserStoryDto {
+ userStoryNumber
+ userStoryText
+ status
}

interface ISprintRepository{
+ findById(sprintIdVO)
}

class UserStoryRepository{
+ getListOfUsWithMatchingIds(usId)
}

interface IUserStoryRepository{
+ getListOfUsWithMatchingIds(usId)
}

class SprintRepository{
+ findById(sprintIdVO)
}

class Sprint<<root>>{
- sprintId
- sprintNumber
- projectCode
- period
- userStoriesInSprint
+ getUserStoriesInSprint()
}

class UserStory<<root>>{
- usId
- acceptanceCriteria
- usNumber
- actor
- usText
- status
- projectCode
}

class UserStoryJpa{
    usId
    acceptanceCriteria
    usNumber
    actor
    usText
    status
    projectCode
}

class UserStoryDomainDataAssembler{
toData(userStory)
}

class FactoryUserStory{
createUserStory(usNumber, usText, actor, acceptanceCriteria, projectCode)
}

interface IUserStoryJpaRepository{
getListOfUsWithMatchingIds(usId)
findAllByUsIdIn(usId)
}

interface CrudRepository{
findAllById(ids)
}

interface IFactoryUserStory{
createUserStory(usNumber, usText, actor, acceptanceCriteria, projectCode)
}

SprintWebController <.. UserStoriesInSprintService: is injected
UserStoriesInSprintService <.. ISprintRepository: is injected
UserStoriesInSprintService <.. IUserStoryRepository: is injected
UserStoriesInSprintService ..> UserStoryMapper: uses
IUserStoryRepository <|.. UserStoryRepository: implements
ISprintRepository <|.. SprintRepository: implements
SprintRepository --> Sprint: has
UserStoryRepository --> UserStory: has
UserStoryMapper ..> UserStoryDto: creates
UserStoryDto ..> UserStory: uses
UserStoryJpa <.. UserStoryDomainDataAssembler: creates
IFactoryUserStory ..> UserStoryDomainDataAssembler: is injected
UserStoryRepositoryJpa "1" --> "*" UserStoryJpa: has
CrudRepository --left|> IUserStoryJpaRepository: extends
IUserStoryJpaRepository ..> UserStoryRepositoryJpa: is injected
IUserStoryJpaRepository ..> UserStoriesInSprintService: is injected
FactoryUserStory --> IFactoryUserStory: implements
FactoryUserStory --> UserStory: creates
@enduml