@startuml
skinparam sequenceMessageAlign center
title TO LIST ALL ACCOUNTS
legend top
US004 - As Administrator, I want to get a list of all user accounts and their status.
end legend
autonumber
actor Administrator
participant ":ListAccountUI" as ui
participant ":ListAccountController" as controller
participant ":AccountService" as Aservice
participant ":AccountRepository" as rep
participant ":AccountMapper" as map
participant ":accountsDto" as accountsDto
participant ":accountsDto" as accountsDto
participant "accountDto:AccountDto" as accountDto

activate Administrator
Administrator -> ui: Lists all accounts
activate ui
ui -> controller: listAllAccounts()
activate controller
controller -> Aservice: listAllAccounts()
activate Aservice
Aservice -> rep: getAccounts()
activate rep
rep --> Aservice: accounts
deactivate rep
Aservice --> controller: accounts
deactivate Aservice
controller -> map : accountToDtoList(accounts)
create "accountsDto"
activate map
map --> accountsDto: create ()

loop for each account in accounts
map -> accountDto:  accountToDto(account)
activate accountDto
accountDto --> map : accountDto
deactivate accountDto
map -> accountsDto: add(accountDto)
end loop

map --> controller : accountsDto
deactivate map

deactivate Aservice
controller -->> ui: accountsDto
deactivate controller
ui -->>Administrator: shows list
deactivate ui

@enduml
