@startuml

skinparam sequenceMessageAlign center
title TO ASSOCIATE/DEFINE TEAM MEMBER/PRODUCT OWNER/SCRUM MASTER OF A PROJECT
legend top
US011 - As Manager, I want to associate a User as Team Member of a project.
US012 - As Manager, I want to define the Product Owner of a project
US013 - As Manager, I want to define the Scrum Master of a project.
end legend

class AddUserToProjectController {
-company
+addUserToProject(emailManager, accountDTO, projectDTO, allocationDTO)
}

class Company {
-accountContainer
-projectContainer
-accountInProjectContainer
+validateManager(emailManager)
+addUserToProject(accountDTO, projectDTO, allocationDTO)
}

class AccountContainer {
-accounts
+validateManager(email)
+getAccountByEmail(accountDTO.email)
}

class ProjectContainer {
-projects
+getProjectByCode(projectDTO.code)
}

class AccountInProject{
-account
-project
-costPerHour
-percentageAllocation
-role
-startDate
-endDate
+AccountInProject(account, project, role, costPerHour, percentageAllocation, startDate)
}

class AccountInProjectContainer{
-accountsInProject
+addUserToProject(account, project, allocationDTO)
}

class "Account"{
-email
-profile
+checkAccountFromEmail(email)
+isManager()
}

class "Profile"{
-profileName
+isManager()
}


AddUserToProjectController "1"-->"1" Company:has
Company "1"-->"1" AccountInProjectContainer: has
Company "1"-->"1" AccountContainer: has
Company "1"-->"1" ProjectContainer: has
AccountInProjectContainer "1"--> "*" AccountInProject: has
"AccountContainer""1" --> "*""Account": has
"Account" "*"--> "1""Profile": has
@enduml



