@startuml
skinparam sequenceMessageAlign center
title TO CONSULT THE PRODUCT BACKLOG
legend top
US018 - As PO/SM/Team Member, I want to consult the product backlog, i.e. to get the list of user stories sorted by priority.
end legend
autonumber

actor "Product Owner\nScrum Master\nTeam Member" as actor
participant ":GetProductBacklogUI" as ui
participant ":GetProductBacklogController" as controller
participant ":ProjectService" as pservice
participant ":ProjectRepository" as prepo
participant ":Project" as project
participant ":ProductBacklog" as backlog
participant ":UsService" as uservice
participant ":UsRepository" as usrep
participant "userStoriesDto"
participant ":userStoryMapper" as usmapper



actor -> ui: requests product backlog (list of all US) from selected project
activate ui
ui -> controller: getProductBacklog(projectCode)
activate controller
controller -> pservice: getProductBacklog(code)
activate pservice
pservice -> prepo: getProjectByCode(code)
activate prepo
prepo -> project: getProductBacklog()
activate project
project -> backlog: getUserStories()
activate backlog
backlog --> project: usIds
deactivate backlog
project --> prepo: usIds
deactivate project
prepo --> pservice: usIds
deactivate prepo
pservice --> controller: usIds
deactivate pservice
controller -> uservice : requestAllPlannedUs(usIds)
activate uservice
uservice -> usrep : getListOfUsWithMatchingIds(usIds)
activate usrep
usrep --> uservice : userStories
deactivate usrep
create "userStoriesDto"
uservice --> userStoriesDto: create ()
loop for each userStory in userStories
uservice -> usmapper:  userStoryToDto(userStory)
activate usmapper
usmapper --> uservice : userStoryDto
deactivate usmapper
uservice -> "userStoriesDto": add(userStoryDto)
activate "userStoriesDto"
deactivate "userStoriesDto"
end loop

uservice --> controller: userStoriesDto
deactivate uservice
controller --> ui : userStoriesDto
deactivate controller

ui --> actor: shows list of all US
deactivate ui
@enduml