@startuml
skinparam sequenceMessageAlign center
title TO CONSULT THE PRODUCT BACKLOG
legend top
US018 - As PO/SM/Team Member, I want to consult the product backlog, i.e. to get the list of user stories sorted by priority.
end legend
autonumber

actor "Product Owner\nScrum Master\nTeam Member" as actor
participant ":GetProductBacklogUI" as ui
participant ":GetProductBacklogController" as controller
participant ":Company" as company
participant ":ProjectContainer" as container
participant ":Project" as project
participant ":ProductBacklog" as backlog
participant ":UserStoryDtoListAssembler" as assembler


actor -> ui: requests list of all projects
activate ui
ref over ui: US016: list of all projects a user is currently allocated to

ui --> actor: shows list of all projects
deactivate ui

actor -> ui: requests product backlog (list of all US) from selected project
activate ui
ui -> controller: getProductBacklog(projectDto)
activate controller
controller -> company: getProductBacklog(projectCode)
activate company
company -> container: getProductBacklog(projectCode)
activate container

container -> project: getProductBacklog()
activate project
project -> backlog: getProductBacklogCopy()

loop for each user story in userStories
activate backlog
backlog -> backlog: getUserStoriesCopy()

backlog --> project: productBacklog
deactivate backlog

project --> container: productBacklog
deactivate project
container --> company: productBacklog
deactivate container
company --> controller: productBacklog
deactivate company
controller -> assembler: backlogToDto(productBacklog)
activate assembler
assembler -> backlog: getUserStoriesCopy()
activate backlog
backlog --> assembler: userStories
deactivate backlog
ref over assembler: To create a user story DTO
assembler --> controller: userStoryDtoList

deactivate assembler
controller --> ui: userStoryDtoList
deactivate controller

ui --> actor: shows list of all US
deactivate ui
@enduml