@startuml
'https://plantuml.com/class-diagram'

title TO CONSULT THE PRODUCT BACKLOG
skinparam sequenceMessageAlign center
legend top
US018 - As PO/SM/Team Member, I want to consult the product backlog, i.e. to get the list of user stories sorted by priority.
end legend

class "ConsultProductBacklogController" {
-projectService
+getProductBacklog(projectCode)
}

class "ProjectService"{
-factoryProject
-projectRepository
-usRepository
-userStoryMapper
+getProductBacklog(code)
+getProjectByCode(code)
+requestAllPlannedUserStories(usIds)
+userStoryToDtoList(userStories)
}


class "Project" <<root>>{
-projectCode
-productBacklog
+hasProjectCode(projectCode)
+getProductBacklog()
}

class "ProductBacklog"{
-userStories
#getUserStories()
}



class "UsRepository"{
-userStories
+getListOfUsWithMatchingIds(usIds)
}

class "UserStoryMapper"{
+userStoryToDto(userStory)
+userStoryToDtoList(userStories)
}

class "UserStory" <<root>>{
-usNumber
-usText
-status
+getUsNumber()
+getUsText()
+getStatus()
}

interface "IProjectRepository" {
+getProjectByCode(code)
}

interface "IUsRepository" {
+getListOfUsWithMatchingIds(usIds)
}

class ProjectRepository{
-projects
+getProjectByCode(code)
}

class "UserStoryDto"{
+userStoryNumber
+userStoryText
+status
}

"ConsultProductBacklogController" "1"<.."1" "ProjectService":  is injected

"Project" "1"-->"1" "ProductBacklog": has
"ProductBacklog" "1"-->"*" "UserStory": has
"ProjectRepository" -> "Project" : contains

"UsRepository" "1"->"*" "UserStory": has
"UserStoryMapper" "1 "..> "*" "UserStoryDto" : creates
"UserStoryMapper" ..> "UserStory" : knows
"ProjectRepository" --|> "IProjectRepository" : implements
"ProjectService" "1"-->"1" "UserStoryMapper" : has
"ProjectService" <.. "IProjectRepository" : is injected
"ProjectService" <.. "IUsRepository" : is injected
"UsRepository" --|> "IUsRepository" :implements
@enduml