@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam sequenceMessageAlign center
title TO ADD BUSINESS SECTOR
legend top
US008 - As Administrator, I want to add a business sector.
end legend

actor Administrator as a
participant ":AddBusinessSectorUI" as ui
participant ":AddBusinessSectorController" as ct
participant ":Company" as c
participant ":BusinessSectorContainer" as cn
participant "businessSector:BusinessSector" as bs

activate a
a -> ui: starts adding new business sector
activate ui
a <-- ui: requests data (name)
a -> ui: types requested data
ui -> ct: addBusinessSector(name, email)
activate ct
ct -> c: validateProfileRequired(email, profileNameRequired)
activate c
ref over c: validateAdministrator_sequenceDiagram
c --> ct: true
deactivate c
ct -> c: addBusinessSector(name)
activate c
c -> cn: addBusinessSector(name)
activate cn
create bs
cn -> bs: create(name)
cn -> cn: add(businessSector)
c <-- cn: true
deactivate cn
ct <-- c: true
deactivate c
ui <-- ct: true
deactivate ct
a <-- ui: informs operation success
deactivate ui

@enduml