@startuml
'https://plantuml.com/class-diagram
skinparam sequenceMessageAlign center
title TO ADD BUSINESS SECTOR
legend top
US008 - As Administrator, I want to add a business sector.
end legend
class AddBusinessSectorController {
-company
+addBusinessSector(name, email)
}


class Company {
-accountContainer
-businessSectorContainer
+validateProfileRequired(email, profileNameRequired)
+addBusinessSector(name)
}

class AccountContainer {
-accounts
+validateProfileRequired(email, profileNameRequired)
+getAccountByEmail(email)
}

class Account {
-email
-profile
+equals(Object toCompare)
+hashCode()
+checkAccountFromEmail(email)
+ isProfileRequired(profileNameRequired)
}

class Profile{
-profileName
+ isProfileRequired(profileNameRequired)
+equals(Object toCompare)
+hashCode()
}

class BusinessSectorContainer {
-businessSectors
+addBusinessSector(name)
-doesBusinessSectorExist(businessSector)
}

class BusinessSector {
-name
+BusinessSector(name)
+equals(Object toCompare)
+hashCode()
}

"AddBusinessSectorController" "1"-->"1" "Company" : has
"Company" "1"-->"1"  "AccountContainer" :has
"AccountContainer" "1"-->"*"  "Account"
"Account" "*"-->"1" "Profile"
"Company" "1"-->"1"  "BusinessSectorContainer"
"BusinessSectorContainer" "1"-->"*"  "BusinessSector"

@enduml