@startuml

skinparam sequenceMessageAlign center
title TO ASSOCIATE USER AS TEAM MEMBER
legend top
US011 - As Manager, I want to associate a User as Team Member of a project.
end legend
autonumber

actor Manager
participant ":AddUserInProjectUI" as ui
participant ":AddUserInProjectController" as controller
participant ":Company" as company
participant "accountInProjectContainer:AccountInProjectContainer" as accinprojcont
participant ":AllocationMapper" as mapper
participant "accountInProject:AccountInProject" as accinproj

Manager -> ui: starts the association of a Team Member to a project
activate ui
/'Manager <-- ui:  requests data (email,projectCode, role)'/
ui -> controller: addTeamMemberToProject(emailManager)
activate controller
controller -> company: validateManager((emailManager)
activate company
ref over company: validateManager_sequenceDiagram
company --> controller: true
deactivate company
controller -> company: listAllUsers()
activate company
ref over company: listAllUSers_sequenceDiagram
company --> controller: users
deactivate company
controller -> company: listAllProjects()
activate company
ref over company: US015_sequenceDiagram
company --> controller: projects
deactivate company
controller --> ui: userAccountsDTO
controller --> ui: projectsDTO
deactivate controller
ui --> Manager: list of all Users/projects

deactivate ui

Manager -> ui: selects user/project
activate ui
Manager -> ui: sends data (costPerHour, percentageAllocation, startDate )
ui -> controller: addTeamMemberToProject(allocationDTO)
activate controller
controller -> company: addTeamMemberToProject(allocationDTO)
activate company
company -> accinprojcont: addTeamMemberToProject(allocationDTO)
activate accinprojcont
accinprojcont -> mapper: addTeamMemberToProject(allocationDTO)
activate mapper
create accinproj
mapper -> accinproj: create(account, project...)
mapper --> accinprojcont: acountInProject
deactivate mapper
accinprojcont -> accinprojcont: add(accountInProject)
accinprojcont --> company: true
deactivate accinprojcont
company --> controller: true
deactivate company
controller --> ui: true
deactivate controller
ui --> Manager: informs team member allocated
deactivate ui


@enduml

