@startuml

skinparam sequenceMessageAlign center
title TO ASSOCIATE USER TEAM MEMBER TO A PROJECT
legend top
US011 - As Manager, I want to associate a User as Team Member of a project.
end legend

class AddUserInProjectController {
-company
+addTeamMemberToProject(emailManager)
+addTeamMemberToProject(allocationDTO)
}

class Company {
-accountInProjectContainer
+addTeamMemberToProject(allocationDTO)
}

class AccountInProject{
-account
-project
-costPerHour
-percentageAllocation
-role
-startDate
-endDate
+createAccountInProject(account, project, role)
}

class AccountInProjectContainer{
-accountsInProjects
-doesAccountExist(accountInProject)
+addTeamMemberToProject(accountInProject)
}

class AllocationMapper {
+addTeamMemberToProject(account, project...)
}

AddUserInProjectController --> Company
Company "1"-->"1" AccountInProjectContainer: has
AccountInProjectContainer "1"..>"1" AllocationMapper
AllocationMapper "1"..> "*"AccountInProject: creates
AccountInProjectContainer "1"--> "*" AccountInProject: has
@enduml