@startuml

skinparam sequenceMessageAlign center
title TO ASSOCIATE USER AS TEAM MEMBER
legend top
US011 - As Manager, I want to associate a User as Team Member of a project.
end legend
autonumber

actor Manager
participant ":AddUserInProjectUI" as ui
participant ":AddUserInProjectController" as controller
participant ":Service" as ser
participant ":Company" as company
participant ":AccountContainer" as acccontainer
participant ":account:Account" as acc
participant "projectContainer:ProjectContainer" as pcontainer
participant "accountInProjectContainer:AccountInProjectContainer" as accinprojcont
participant "accountInProject:AccountInProject" as accinproj


Manager -> ui:  associate User as Team Member
activate ui
Manager <-- ui:  requests data (email,projectCode, role)
deactivate ui
Manager -> ui:  enters data
activate ui
ui -> controller: addUserInProject(email, projectCode, role)
activate controller
controller -> ser: addUserInProject(email, projectCode, role)
activate ser
company <- ser: validateManager(email)
activate company
company <- ser: addUserInProject(email, projectCode, role)
company -> acccontainer: validateManager(email)
activate acccontainer
acccontainer -> acccontainer: account=getAccountByEmail(email)
acccontainer -> acc: isManager()
activate acc
acccontainer <-- acc: true
deactivate acc
acccontainer --> company: true
company --> ser: true
deactivate acccontainer
ser -> company: getProject(projectCode)
company -> pcontainer:getProject(projectCode)
activate pcontainer
company <-- pcontainer: project
deactivate pcontainer
ser <-- company: project
accinprojcont <- company: createAccountInProject(account, project, role)
activate accinprojcont
create accinproj
accinprojcont -> accinproj: create(account, project, role)
'https://stackoverflow.com/questions/27001842/how-to-draw-calls-from-constructors-in-uml-sequence-diagrams

accinprojcont -> accinprojcont: add(accountInProject)
accinprojcont --> company: true
deactivate accinprojcont
company --> ser: true
deactivate company
ser --> controller: true
deactivate ser
controller --> ui: true
deactivate controller
ui -->> Manager: informs successful association
@enduml