@startuml
skinparam sequenceMessageAlign center
title TO CREATE NEW PROFILE
legend top
US001 - As Administrator, I want to create user profiles.
end legend
actor Administrator
autonumber
Administrator  -> ":System": Create new profile
note left
Account is authenticated.
System grants access.
end note
":System" --> Administrator: Returns data (profile name, profile permissions)
Administrator -> ":System": Enters profile data
":System" --> Administrator: New profile created
@enduml

@startuml
legend top
US002 - As Administrator, I want to Register a user.
end legend
skinparam sequenceMessageAlign center
title TO REGISTER NEW ACCOUNT
autonumber
actor Administrator
Administrator -> ":System": Create new Account
note left
Account is authenticated.
System grants access.
end note
Administrator <-- ":System": Returns data (account name, account e-mail, etc)
Administrator  -> ":System": Enters account data
":System" --> Administrator: New profile created
@enduml

@startuml
legend top
US003 - As Administrator, I want to change the profile of a user account.
end legend
skinparam sequenceMessageAlign center
title TO CHANGE PROFILE
actor Administrator
autonumber
Administrator -> ":System": Request account info
note left
Account is authenticated.
System grants access.
end note
":System" --> Administrator: Returns account info
Administrator -> ":System": Change account data (profile type)
":System" --> Administrator: Profile was updated
@enduml

@startuml
legend top
US004 - As Administrator, I want to get a list of all user accounts and their status.
end legend
skinparam sequenceMessageAlign center
title TO LIST ALL ACCOUNT
actor Administrator
autonumber
Administrator -> ":System": Request list of all accounts and status
note left
Account is authenticated.
System grants access.
end note
":System" --> Administrator: Returns data
@enduml

@startuml
skinparam sequenceMessageAlign center
title TO SEARCH ACCOUNT BY E-MAIL
actor Administrator
autonumber
Administrator -> ":System": Search account by e-mail
note left
Account is authenticated.
System grants access.
end note
":System" --> Administrator: Returns data
@enduml

@startuml
skinparam sequenceMessageAlign center
title TO SEARCH ACCOUNT BY PROFLIE
actor Administrator
autonumber
Administrator -> ":System": Search account by profile
note left
Account is authenticated.
System grants access.
end note
":System" --> Administrator: Returns list of accounts
@enduml
@startuml
legend top
US005 - As Administrator, I want to activate a user account.
end legend
skinparam sequenceMessageAlign center
title TO ACTIVATE USER ACCOUNT
actor Administrator
autonumber
Administrator -> ":System": Request account Info
note left
Account is authenticated.
System grants access.
end note
":System" --> Administrator: Returns account Info
Administrator -> ":System": Change the status to "Active"
":System" --> Administrator: Status was updated
@enduml

@startuml
legend top
US006 - As Administrator, I want to inactivate a user account.
end legend
skinparam sequenceMessageAlign center
title TO INACTIVATE USER ACCOUNT
actor Administrator
autonumber
Administrator -> ":System": Request account info
note left
Account is authenticated.
System grants access.
end note
Administrator <-- ":System": Returns account info
Administrator -> ":System": Change the status to "Inactive"
":System" --> Administrator: Status was updated
@enduml

@startuml
skinparam sequenceMessageAlign center
title TO CREATE PROJECT
autonumber
actor Manager
Manager -> ":System": Create new Project
note left
Account is authenticated.
System grants access.
end note
Manager <-- ":System": Returns data (name, description, etc)
Manager -> ":System":  Enters project data
Manager <-- ":System": New project created
@enduml

@startuml
skinparam sequenceMessageAlign center
title TO MANAGE PROJECT
actor "Product Manager" as PM
autonumber
PM -> ":System": Edit project Information
note left
Account is authenticated.
System grants access.
end note
PM <-- ":System": Project information Updated
@enduml

@startuml
skinparam sequenceMessageAlign center
title TO SEARCH PROJECT BY MANAGER
actor Manager
autonumber
Manager -> ":System": Search Project by(code, name, etc)
note left
Account is authenticated.
System grants access.
end note
Manager <-- ":System": List of all Projects
@enduml

@startuml
skinparam sequenceMessageAlign center
title TO SEARCH PROJECT BY USER
actor User
autonumber
User -> ":System": Search Project by(code, name, etc)
note left
Account is authenticated.
System grants access.
end note
User <-- ":System": List of some Projects where User is/was enrolled.
@enduml

@startuml
skinparam sequenceMessageAlign center
title TO CREATE USER STORIES
actor "Product Owner" as PO
autonumber
PO -> ":System": Create new User Story
note left
Account is authenticated.
System grants access.
end note
PO <-- ":System": Returns data (US number, Actor, priority in PB, etc)
PO -> ":System": Enters User Story data
PO <-- ":System": User Story created and added to PB
@enduml

@startuml
skinparam sequenceMessageAlign center
title TO CREATE SPRINT
actor Team
autonumber
Team -> ":System": Request product Backlog data
note left
Account is authenticated.
System grants access.
end note
Team <-- ":System": Returns User Stories
Team -> ":System": Defines User Stories for Sprint
Team <-- ":System": New Sprint created
@enduml

@startuml
skinparam sequenceMessageAlign center
title TO GROOM USER STORIES
actor "Product Owner" as PO
PO -> ":System": Request product Backlog data
note left
Account is authenticated.
System grants access.
end note
PO <-- ":System": Returns User Stories
PO -> ":System": Decompose User Story
PO <-- ":System": User Story was replaced
@enduml

2.4.3 Sprint review
@startuml
Team -> System: Access to product Backlog
Team <-- System: Returns product Backlog
Team -> System: Sprint backlog and effort Definition
Team <-- System: Sprint backlog Defined
@enduml

2.4.3 Tasks for us
@startuml
actor "Product Owner" as PO
Team -> System: Registers finished Task
System -> System: Finished US
System -> System: Product backlog\nUpdated \n
PO -> System: Request the finished US
PO <-- System: Retrieves finished US
PO -> System: Update product backlog\nwith rejected US
@enduml

2.4.4 Task update
@startuml
actor Account
Account -> System:1 Access Information
System --> Account:2 Grants Access
Account -> System:3 Updates Information
Account -> System:4 Completes the comment Field
System --> Account:5 Generates a Record
@enduml

2.4.5  Project allocation
@startuml
actor Manager
Manager -> System:1 Access System
System --> Manager:2 Grants Access
Manager -> System:3 Checks available Resources
System --> Manager:4 Shows available Resources
Manager -> System:5 Choose resource and select Project
System --> Manager:6 System assigns resource to Project
@enduml

2.4.6 Project activity
@startuml
skinparam sequenceMessageAlign center
autonumber
title TO CHECK PROJECT ACTIVITY
actor Account
Account -> System: View project activity Status
Account -> System: Choose what type of View
System --> Account: Returns a table-shaped View
System --> Account: Returns a Gantt form View
@enduml

2.4.7
@startuml
skinparam sequenceMessageAlign center
autonumber
title TO GENERATE ALLOCATION REPORT
actor Manager
Manager -> System: Requests allocation report for any project and any member
System --> Manager: Generates Report
@enduml

@startuml
skinparam sequenceMessageAlign center
autonumber
title TO GENERATE ALLOCATION REPORT
actor "Product Owner" as PO
PO -> System: Requests allocation report of any member of the projects he/she/they is involved in
System --> PO: Generates Report
@enduml

@startuml
skinparam sequenceMessageAlign center
autonumber
title TO GENERATE ALLOCATION REPORT
actor "Scrum Master" as SM
SM -> System: Requests allocation report of any member of the projects he/she/they is involved in
System --> SM: Generates Report
@enduml

@startuml
skinparam sequenceMessageAlign center
autonumber
title TO GENERATE ALLOCATION REPORT
actor "Team Member" as TM
TM -> System: Requests allocation Report of the project he/she/they is involved
System --> TM: Generates Report
@enduml

2.4.8
@startuml
skinparam sequenceMessageAlign center
autonumber
title TO GENERATE A KPI REPORT
actor Manager
Manager -> System: Requests KPI Report any of Project
System --> Manager: Chooses XML file or on Screen
Manager -> System: Selects XML file or on Screen
System --> Manager: Reports CPI and SPI in chosen Format
@enduml

@startuml
skinparam sequenceMessageAlign center
autonumber
title TO GENERATE A KPI REPORT
actor "Project Manager" as PM
PM -> System: Requests KPI Report of Project he/she/they is involved
System --> PM: Chooses XML file or on Screen
PM -> System: Selects XML file or on Screen
System --> PM: Reports CPI and SPI in chosen Format
@enduml

@startuml
skinparam sequenceMessageAlign center
autonumber
title TO GENERATE A KPI REPORT
actor "Product Owner" as PO
PO -> System: Requests KPI Report of Project he/she/they is involved
System --> PO: Chooses XML file or on Screen
PO -> System: Selects XML file or on Screen
System --> PO: Reports CPI and SPI in chosen Format
@enduml