@startuml
class Administrator{
+createNewProfile(name, permissions)
+changeProfile(email,profile)
+insertUserInformation(email),(profile)
+registerAccount(name, email, phoneNumber)
+listAccountsAndStatus(email),(status)
+changeStatusToInactive(status)
+changeStatusToActive(status)
}
class Profile{
-profile
+createProfile(profile)
}
class Account {
-name
-email
-phoneNumber
+Account(name, email, phoneNumber)
+ updateStatus(inactive)
+ updateStatus(active)
+ updateProfile (email, profile)
-email
-status
+getemail()
+getstatus()
}

class "CreateProfile:Controller" {
+validateProfile(profile)
+saveProfile(profile)
-addProfile(profile)
}
class "RegisterAccount:Controller" {
+registerNewAccount(name, email phoneNumber)
+validateAccount(account)
-addAccount(account)
}
class ChangeStatusController{
+changesStatus(inactive)
+isStatusValid(inactive)
+changesStatus(active)
+isStatusValid(active)
}
class ChangeProfileController {
+isUserValid(email)
+isProfileValid(profile)
}
class "AccountListController" {
+createInfo(email, status)
}

class AccountList{
+addToList(accountInfo)
+accountInfo(email, status)
}

hide Profile circle
hide "CreateProfile:Controller" circle
hide Administrator circle
hide "RegisterAccount:Controller" circle
hide Account circle
hide ChangeStatusController circle
hide Account circle
hide ChangeStatusController circle
hide Account circle
hide ChangeProfileController circle
hide Account circle
hide Administrator circle
hide "Account" circle
hide "AccountList" circle
hide "AccountListController" circle

Administrator <|-- "CreateProfile:Controller"
Administrator <|-- "RegisterAccount:Controller"
Administrator <|-- ChangeStatusController
Administrator <|-- ChangeProfileController
Administrator <|-- "AccountListController"

"CreateProfile:Controller" "1" --> "*" Profile: creates
"RegisterAccount:Controller" "1" --> "*" Account: contains
ChangeStatusController "1" -->"*"Account: changes
ChangeProfileController "1" -->"*"Account: changes
"AccountListController" "1" --> "*" Account: gets
Account *-- AccountList


@enduml