
@startuml

skinparam sequenceMessageAlign center
title TO DEFINE THE SCRUM MASTER OF A PROJECT
legend top
As Manager, I want to define the Scrum Master of a project.
end legend

class DefinesAScrumMasterController {
-service
+definesAScrumMaster(email, projectCode)
}
class Service {
-company
+definesAScrumMaster(email, projectCode)
}
class Company {
-accountContainer
-projectContainer
-accountInProjectContainer
+validateManager(email)
+getAccountByEmail(email)
}
class AccountContainer {
-account
+validateManager(email)
+getAccountByEmail(email)
}
class Account {
-email
+validateManager(email)
}
class ProjectContainer{
-project
+getProject(project)
}
class AccountInProjectContainer{
-accountInProject
+definesAScrumMaster(account, project)
+addToContainer()
-verifyIfAccountInProjectExists(accountInProject)
}
class AccountInProject{
-account
-project
-role
+definesAScrumMaster(account, project)
}
AccountContainer --> Account
DefinesAScrumMasterController ..> Service
Service --> Company
Company "1       " --> "*"AccountContainer: has
Company "1"--> "        *"ProjectContainer: has
Company "1 "-->"*" AccountInProjectContainer: has
AccountInProjectContainer "    1"--> "   *"AccountInProject: contains
@enduml