@startuml
skinparam sequenceMessageAlign center
title ESTIMATE USER STORY EFFORT
legend top
US021 - As Team Member, I want to estimate the effort of a user story in a sprint, during the sprint planning ceremony
end legend
autonumber
actor TeamMember
participant ":EstimateUserStoryEffortUI" as ui
participant ":EstimateUserStoryEffortController" as controller
participant ":Company" as company
participant ":ProjectContainer" as pc
participant ":Project" as project
participant ":Sprint" as sprint
participant ":SprintBacklog" as sb
participant ":UserStory" as us


activate TeamMember

TeamMember -> ui: requests list of projects
activate ui
ref over ui: US016:As Authenticated User, I want to get a list of all projects I'm currently allocated to
ui --> TeamMember: request data

TeamMember -> ui: requests list of user stories
ref over ui: US022: As Team Member, I want to view the Scrum Board of current sprint.
ui --> TeamMember: request data


TeamMember -> ui: selects data and estimate effort (userStoryDto, effort, projectDto)



ui -> controller: estimateEffortUserStory(userStoryDto, effort, projectDto)
activate controller

controller -> company: estimateEffortUserStory (UseruserStoryDto, effort, projectDto, date)
activate company

company -> pc: estimateEffortUserStory (userStoryDto, effort, projectCode, date)
activate pc

pc -> project: estimateEffortUserStory (userStoryDto, effort, date)
activate project

project -> sprint: estimateEffortUserStory (userStoryDto, effort)
activate sprint

sprint -> sb: estimateEffortUserStory (userStoryDto, effort)
activate sb
note right of us: fetches in class enum the effort value pretended

sb -> us: setEffort(effort)
activate us

us -> us: setEffort

sb --> sprint: true
deactivate us
deactivate sb
sprint --> project: true
deactivate sprint
project --> pc: true
deactivate project
pc --> company: true
deactivate pc
company --> controller: true
deactivate company
controller --> ui: true

deactivate controller
ui --> TeamMember: shows success message
deactivate ui
@enduml