@startuml
legend top
US007 - As Administrator, I want to create a new Project Typology.
end legend
skinparam sequenceMessageAlign center
title TO CREATE NEW PROJECT TYPOLOGY
actor Administrator
autonumber
Administrator -> ":System": starts creating new project typology
note left
Account is authenticated.
":System" grants access.
end note
":System" --> "Administrator": requests data (projectTypology)
Administrator -> ":System": types requested data
Administrator <-- ":System": informs operation success
@enduml


@startuml
legend top
US008 - As Administrator, I want to add a business sector.
end legend
skinparam sequenceMessageAlign center
title TO CREATE A NEW BUSINESS SECTOR
actor "Administrator"
autonumber
Administrator -> ":System": starts adding new business sector
note left
Account is authenticated.
":System" grants access.
end note
Administrator <-- ":System": requests data (name)
Administrator -> ":System": types requested data
Administrator <-- ":System":informs operation success
@enduml


@startuml
legend top
US009 - As Administrator, I want to add a customer.
end legend
skinparam sequenceMessageAlign center
title TO ADD A CUSTOMER
actor "Administrator"
autonumber
Administrator -> ":System": starts adding new customer
note left
Account is authenticated.
":System" grants access.
end note
Administrator <-- ":System": requests data (customerName, customerNIF)
Administrator-> ":System": sends requested data
Administrator <-- ":System":informs operation success
@enduml


@startuml
legend top
US010 - As Manager, I want to register/create a new project.
end legend
skinparam sequenceMessageAlign center
title TO REGISTER NEW PROJECT
autonumber
actor "Manager"
"Manager" -> ":System": registers new project
note left
Account is authenticated.
":System" grants access.
end note
"Manager" <-- ":System": requests data (code, name, ...)
"Manager" -> ":System":  types requested data
"Manager" <-- ":System": informs project created
@enduml

@startuml
legend top
US011 - As Manager, I want to associate a user as Team Member of a project.
US012 - As Manager, I want to define the PO of a project.
US013 - As Manager, I want to define the SM of a project.
end legend
skinparam sequenceMessageAlign center
title TO ASSOCIATE USER AS TEAM MEMBER/PRODUCT OWNER/SCRUM MASTER TO A PROJECT
actor "Manager"
autonumber
"Manager" -> ":System": requests list of all User accounts
note left
Account is authenticated.
":System" grants access.
end note
"Manager" <-- ":System": requests to select User account
"Manager" -> ":System": selects User account
"Manager" -> ":System": requests list of all projects
"Manager" <-- ":System": requests to select project
"Manager" -> ":System": selects project
"Manager" -> ":System": starts the association of the selected User with the selected project and a role
"Manager" <-- ":System": requests data
"Manager" -> ":System": sends data (role, costPerHour, percentageAllocation, startDate)
"Manager" <-- ":System": informs team member/product owner/scrum master associated/defined
@enduml

@startuml
legend top
US014 - As Manager, I want to get a list of all human resources in a project.
end legend
skinparam sequenceMessageAlign center
title TO GET A LIST OF ALL HUMAN RESOURCES IN PROJECT
actor "Manager"
autonumber
"Manager" -> ":System": requests a list of all human resources in project
note left
Account is authenticated.
":System" grants access.
end note
":System" --> Manager: request data (projectCode)
"Manager" -> ":System": types requested data
"Manager" <-- ":System": shows list of accounts
@enduml

@startuml
legend top
US015 - As Manager, I want to get a list of all projects.
end legend
skinparam sequenceMessageAlign center
title TO GET A LIST OF ALL PROJECTS
actor "Manager"
autonumber
"Manager" -> ":System": get list of all projects
note left
Account is authenticated.
":System" grants access.
end note
"Manager" <-- ":System": request data (email)
"Manager" -> ":System": types requested data
"Manager" <-- ":System": shows list all projects
@enduml


@startuml
legend top
US016 - As Authenticated User, I want to get a list of all projects I'm currently allocated to.
end legend
skinparam sequenceMessageAlign center
title TO GET A LIST OF ALL PROJECTS
actor actor
autonumber
actor -> ":System": lists all projects the user is allocated to
note left
Account is authenticated.
":System" grants access.
end note
actor <-- ":System": request data (email)
actor -> ":System": types requested data
actor <-- ":System": shows list of projects

@enduml
