# Use root/admin as user/password credentials
version: '3.1'

services:
  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_USER: switch
      MARIADB_PASSWORD: switch
      MARIADB_DATABASE: g4db
    networks:
      - g4Network
    ports:
      - '3306:3306'
    volumes:
      - database-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
    networks:
      - g4Network
    ports:
      - '8081:80'

  frontend:
    image: 'marianazancheta/g4:frontend31'
    networks:
      - g4Network
    ports:
      - '3000:3000'

  backend:
    image: 'marianazancheta/g4:backend31'
    environment:
      spring.datasource.url: jdbc:mariadb://database:3306/g4db
      spring.datasource.driver-class-name: org.mariadb.jdbc.Driver
      spring.datasource.username: switch
      spring.datasource.password: switch
    networks:
      - g4Network
    ports:
      - '8080:8080'
    depends_on:
      - database

networks:
  g4Network:

volumes:
  database-data:
