@startuml

Class Account{
account_name
email
phoneNumber
photo
account_status
}
hide Account circle



Class Profile{
profile_name
}
hide Profile circle
class Profile
note left: Can be:\n- User\n- Manager\n- Administrator



Class Role{
role_name
}
hide Role circle
class Role
note right: Can be:\n- Product Owner\n- Scrum Master\n- Project Manager\n- Team Member



Class Project{
projectCode
projectName
projectStatus
}
hide Project circle



Class Typology{
typologyName
}
hide Typology circle
class Typology
note right: Can be:\n- Fixed Cost\n- Time and Materials



Class BusinessSector{
businessSectorName
}
hide BusinessSector circle



Class Customer{
customerName
nif
}
hide Customer circle



Class UserStory{
userStoryNumber
actor
userStoryText
status
projectCode
effort
listOfAcceptanceCriteria
}
hide UserStory circle



Class Task{
task_name
task_startDate
task_endDate
task_description
task_effortEstimate
hoursSpent
percentageOf_execution
type
task_status
responsible
}
hide Task circle



Class Sprint {
sprintNumber
period
}
hide Sprint circle



Class ProductBacklog{
}
hide ProductBacklog circle



Class SprintBacklog{
}
hide SprintBacklog circle



Class Report {
report_type
date
}
hide Report circle
class Report
note right: Can be:\n- KPI\n- Allocation



Class AccountInProject{
account
project
costPerHour
percentageOf_allocation
startDate
endDate
}
hide AccountInProject circle
class AccountInProject
note right: AccountInProject must have\n"User" profile


Account "1" -- "*" AccountInProject: works in
AccountInProject "*" -- "1" Project: associates
Account "*" -- "1" Profile: has
Project "1" -- "*" Sprint: is divided into
Sprint "1" -- "*" Task: has
Project "1" -- "1" ProductBacklog: has
Project "*" -- "1" Typology: has
Project "*" -- "1" Customer: has
Project "*" -- "1" BusinessSector: has
ProductBacklog "1" -- "*" UserStory: contains
Sprint "1" -- "1" SprintBacklog: has
SprintBacklog "1"--"*" UserStory: contains
UserStory "1"-- "*" Task: contains
AccountInProject "1" -- "*" Report: is generated of
Role "1" -- "*" AccountInProject: has

@enduml