@startuml
title Domain model v.01 \n Dec 14, 2022
hide empty member
hide Account circle
hide Profile circle
hide UserStory circle
hide UserInProject circle
hide Sprint circle
hide Task circle
hide Project circle
hide Role circle

Class Account {
name
email
password
status
photo
}

Class Profile

Class UserInProject

Class Role

Class Project {
code
name
description
startingDate
sprintDuration
numberOfSprints
endingDate
customer
typology
budget
projectManager
productOwner
scrumMaster
projectTeam
projectStatus
}

Class Sprint {
effort
}

Class UserStory {
number
actor
userStoryText
acceptanceCriteria
}

Class Task {
name
description
userStory
startingDate
endingDate
hoursSpent
effortEstimate
percentExecution
type
status
responsible
}

Account "*"--"1" Profile : has >
note left: Administrator \nUser \nManager
Account "1"--"*" UserInProject : is a >
UserInProject "*"--"1" Role : has >
note left: Project Manager \nProduct Owner \nScrum Master \nTeam Member
UserInProject "*"--"1" Project : works in >
Project "1"--"*" Sprint : comprises >
Project "1"--"*" UserStory : contains >
Sprint "1"--"*" Task : contains >
Sprint "1"--"*" UserStory : works in >



@enduml