@startuml
skinparam sequenceMessageAlign center
title TO ADD A USER STORY TO THE SPRINT BACKLOG
legend top
US020 - As Team Member, I want to add a user story in the product backlog to the sprint backlog, during the sprint planning ceremony.
end legend
autonumber
actor "Team Member"
participant ":ListAccountsInProjectUI" as ui
participant ":AddUserStoryToSprintBacklogController" as ct
participant ":Company" as c
participant ":ProjectContainer" as pc
participant "project:Project" as p
participant ":ProductBacklog" as containner
participant "userStory:UserStory" as us
participant "sprint:Sprint" as s
participant ":Sprint Backlog" as sb


activate "Team Member"

"Team Member"-> ui: starts adding a User Story to Sprint Backlog
ref over ui: us018: consult the product backlog_sequenceDiagram
activate ui
ui --> "Team Member": requests data (userStoryDto, sprintNumber)
"Team Member" -> ui: sends requested data
ui -> ct: addUserStoryToSprintBacklog(userStoryDto, sprintNumber)
activate ct
ct -> c: addUserStoryToSprintBacklog(userStoryDto, sprintNumber)
activate c
c -> pc: addUserStoryToSprintBacklog(userStoryDto, sprintNumber)
activate pc

pc -> p : addUserStoryToSprintBacklog(userStoryNumber, sprintNumber)
activate p
p -> containner : getUserStoryByNumber(userStoryNumber)
activate containner
deactivate us
containner --> p : userStory
deactivate containner
p -> s : addUserStoryToSprintBacklog(userStory)
activate s
s -> sb : addUserStory(userStory)
activate sb
sb --> s : true
deactivate sb
s --> p : true
deactivate s
p -> containner : removeUserStory(userStory)

activate containner
containner --> p : true
deactivate containner
p --> pc : true
deactivate p
pc --> c : true
deactivate pc
c --> ct : true
deactivate c
ct --> ui : true
deactivate ct
ui --> "Team Member": User Story was added to Sprint Backlog
deactivate ui

@enduml