@startuml
'https://plantuml.com/sequence-diagram
legend top
US020 - As Team Member, I want to add a user story in the product backlog to the sprint backlog, during the sprint planning ceremony.
end legend
skinparam sequenceMessageAlign center
title  To add a user story in the product backlog to the sprint backlog, during the sprint planning ceremony.

class "AddUserStoryToSprintBacklogController" {
- company
+ addUserStoryToSprintBacklog(projectCode, userStoryDto, sprintNumber)
}

class "Company" {
- projectContainer
+ addUserStoryToSprintBacklog(projectCode, userStoryNUmber, sprintNumber)
}
class "ProjectContainer" {
- projects
+ addUserStoryToSprintBacklog(projectCode, userStoryNumber, sprintNumber)
- getProjectByProjectCode(projectCode)

}

class "Project"{
- projectCode;
- sprints;
- productBacklog;
- iFactoryProductBacklog;
- iFactoryUserStory;
- iFactorySprintBacklog;
- iFactorySprint;
+ addUserStoryToSprintBacklog(userStoryNumber, sprintNumber)
+ hasProjectCode(projectCode)
- getSprintByNumber(sprintNumber)
}

class "ProductBacklog" {
- userStories
- iFactoryUserStory
+ getUserStoryByNumber(userStoryNumber)
+ removeUserStory(userStory)
}

class "UserStory"{
- userStoryNumber
- actor
- userStoryText
- status
- listOfAcceptanceCriteria
- effort
+ hasUserStoryNumber(userStoryNumber)
}

class "Sprint"{
- sprintNumber
- period
- sprintBacklog
- iFactorySprintBacklog
+ Sprint(sprintNumber, factoryPeriod)
+ hasSprintNumber(sprintNumber)
+ addUserStoryToSprintBacklog(userStory)
}

class "SprintBacklog" {
- userStories
+addUserStory(userStory)
}

"AddUserStoryToSprintBacklogController" "1"-->"1" "Company": has
"Company" "1"--> "1" "ProjectContainer": has
"ProjectContainer" "1"-->"*" "Project": contains
"Project" "1" -->"1" "ProductBacklog": has
"Project" "1" -->"*" "Sprint": has
"Sprint" "1" --> "1" "SprintBacklog": has
"SprintBacklog" "1" --> "*" UserStory: contains
"ProductBacklog" "1" --> "*" "UserStory" : contains

@enduml

