@startuml
'https://plantuml.com/sequence-diagram
legend top
US020 - As Project Manager, I want to add a user story to the open/current sprint backlog using the web UI.
end legend
skinparam sequenceMessageAlign center
title  To add a user story to the open/current sprint backlog using the web UI.

class "SprintWebController" {
addUserStoryToSprintBacklogService
+ addUserStoryToSprintBacklog(dto)
}
SprintWebController "1"..>"1" AddUserStoryToSprintBacklogService

class "AddUserStoryToSprintBacklogService" {
- ISprintRepository
- IUsRepository
+ addUserStoryToSprintBacklog(dto)
- getSprintById (sprintId)
- hasUserStoryStatus (usId)
- getUserStory (usId)
}
AddUserStoryToSprintBacklogService "1"..>"1" IUsRepository
AddUserStoryToSprintBacklogService "1"..>"1" ISprintRepository
AddUserStoryToSprintBacklogService "1"..>"1" UserStory
AddUserStoryToSprintBacklogService "1"..>"1" Sprint

interface "ISprintRepository" {
- sprints
+ findById(sprintId)
}
ISprintRepository "1"-->"*" Sprint

interface "IUsRepository" {
- userStories
+ getListOfUsWithMatchingIds(usIdList)
}
IUsRepository "1"-->"*" UserStory

class "UserStory"{
- usId
- acceptanceCriteria
- usNumber
- actor
- usText
- status
- projectCode
+ hasStatus(status)
}

class "Sprint"{
- sprintId
- sprintNumber
- projectCode
- period
- userStoriesInSprint
-status
+ isOpen()
+ addUserStory(usIdVO)
}

@enduml