@startuml

left to right direction
actor "Scrum Master" as scrum
actor "User in Project" as usr
actor "Manager" as mg
actor "Product Owner" as po
actor "Team Member" as tm
actor "Project Manager" as pm
actor "Administrator" as admin



rectangle System {
  usecase "Create Project" as UC1
  usecase "Manage Project" as UC2
  usecase "Search Project" as UC3
  usecase "List Accounts" as UC4
  usecase "Create User Story" as UC5
  usecase "Groom User Story " as UC6
  usecase "Review Sprint" as UC7
  usecase "Create Task" as UC8
  usecase "Update Task " as UC9
  usecase "Allocate Resources" as UC10
  usecase "Generate Allocation Report" as UC11
  usecase "Generate KPI Report" as UC12
  usecase "Create Sprint" as UC13
  usecase "Scrum Recording" as UC14
  usecase "Search Account" as UC15
  usecase "Register Account" as UC16
  usecase "Change Account Profile" as UC17
  usecase "Create Profile" as UC18
  usecase "Activate User Account" as UC19
  usecase "Inactivate User Account" as UC20
  usecase "Register Finished Task" as UC21

}

mg -- UC1
pm -- UC2
mg -- UC3
usr -- UC3
admin -- UC4
po -- UC5
po -- UC6
po -- UC7
usr -- UC8
usr -- UC9
mg -- UC10
mg -- UC11
pm -- UC11
po -- UC11
scrum -- UC11
tm -- UC11
mg -- UC12
pm -- UC12
po -- UC12
usr -- UC13
usr -- UC14
admin -- UC15
admin -- UC16
admin -- UC17
admin -- UC18
admin -- UC19
admin -- UC20
usr -- UC21

@enduml
