@startuml

skinparam sequenceMessageAlign center
title TO REGISTER NEW PROJECT
legend top
US010 - As Manager, I want to register/create a new project.
end legend
autonumber

actor Manager as mg
participant ":RegisterProjectUI" as ui
participant ":RegisterProjectController" as controller
participant ":Company" as comp
participant ":ProjectContainer" as PC
participant ":ProjectMapper" as mapper
participant "project:Project" as project
participant ":dto:ProjectDTO" as dto

activate mg
mg ->ui : register new project
activate ui
ui -->> mg: requests data (code, name, ...)
deactivate ui
mg -> ui: types requested data
activate ui
create dto
ui -> dto: create (code, name, ...)
ui -> controller: registerProject(dto, email)
activate controller

controller -> comp: validateManager(email)
ref over comp: validateManager_sequenceDiagram
activate comp
comp -->> controller: true
deactivate comp
controller -> comp: registerProject(dto)
activate comp
comp -> PC : registerProject(dto)
activate PC
PC -> mapper: createProject(dto)
activate mapper
create project
mapper -> project : create (code, name, ...)
mapper -->> PC: project
deactivate mapper
PC -> PC : addProject(project)
PC -->> comp : true
deactivate PC
comp -->>controller: true
deactivate comp
controller -->> ui : true
deactivate controller
ui -->> mg :  informs project created
deactivate ui

@enduml