@startuml

skinparam sequenceMessageAlign center
title TO REGISTER NEW PROJECT
legend top
US010 - As Manager, I want to register/create a new project.
end legend

class RegisterProjectController {
- company
+ registerProject(projectDto, email)
}


class Company {
- projectContainer
- accountContainer
+ validateProfileRequired(email, profileNameRequired)
+ registerProject(projectDto)
}
class AccountContainer {
- Accounts
+ validateProfileRequired( email, profileNameRequired)
}

class Account {
+ isProfileRequired(profileNameRequired)
- profile
}

class Profile {
-profileName
}

class ProjectContainer {
- projects
+ registerProject(projectDtoAsManager)
}

class ProjectMapper{
+ ProjectDtoAsManager(code, name, customerName, customerNif, projectTypology, businessSector)
+ getProjectFromDto(projectDtoAsManager)
}
class ProjectDtoAsManager{
+ code
+ name
+ status
+ customer
+ projectTypology
+ businessSector
}

class Project{
- code
- name
- status
- customer
- projectTypology
- businessSector
+Project( projectCode, name, customer, projectTypology, businessSector)
}

RegisterProjectController "1"-->"1" Company: has
Company "1"-->"1" ProjectContainer: has
Company "1"-->"1" AccountContainer: has
AccountContainer "1"-->"*" Account: contains
Account "1"-->"1" Profile: has
ProjectMapper "1"..>"*" ProjectDtoAsManager
ProjectContainer "1" ..> "1" "ProjectMapper"
RegisterProjectController "1"..>"1" "ProjectMapper"
ProjectMapper "1"..>"*" Project
ProjectContainer "1" -left-> "*" Project: contains
@enduml
