@startuml

legend top
US016 - As Authenticated User, I want to get a list of all projects I'm currently allocated to.
end legend
skinparam sequenceMessageAlign center
title LIST ALL PROJECTS THE AUTHENTICATED USER IS ALLOCATED TO

class ":ListProjectInAccountController" {
- company
+ listProjectsByAccount(emailUser)
}

class "Company" {
- accountInProjectContainer
+validateProfileRequired(email, profileNameRequired)
+ listProjectsByAccount(email)
}

class "AccountContainer" {
-accounts
+validateProfileRequired(email, profileNameRequired)
+getAccountByEmail(email)
}

class "Account" {
-email
-profile
-status
+equals(Object toCompare)
+hashCode()
+checkAccountFromEmail(email)
+isProfileRequired(profileNameRequired)
+getAccountName()
+getEmail()
+getAccountStatus()
}

class "Profile"{
-profileName
+isProfileRequired(profileNameRequired)
+equals(Object toCompare)
+hashCode()
}

class "AccountInProjectContainer"{
- accountInProject
+ listProjectsByAccount(email)
}

class "AccountInProject"{
-account
-project
-role
-startDate
-costPerHour
-percentageAllocation
-endDate
-validate(email)
+ getProjectByAccount(email)
}

class "ProjectMapper"{
+getListOfProjectsDto(projects)
+getDtoFromProject(project)
}

class "ProjectDto"{
+code;
+name;
+customer;
+status;
+projectTypology;
+businessSector
+equals(Object toCompare)
+hashCode()
}

class "Project"{
-projectCode
-projectName
-customer
-projectStatus
-projectTypology
-businessSector
+equals(Object toCompare)
+hashCode()
+getProjectCode()
+getProjectName()
+getCustomer()
+getProjectStatus()
+getProjectTypology()
+getBusinessSector()
}

"ProjectMapper" ..> "Project"
":ListProjectInAccountController"-->"Company"
"Company" "1"--> "     1""AccountInProjectContainer": has
"Company" "1   " --> "     1" "AccountContainer": has
"AccountInProjectContainer" "1"--> "*" "AccountInProject": has
"AccountContainer" "1" --> "*" "Account": has
"Account" "1" --> "1""Profile": has
":ListProjectInAccountController"..> "ProjectMapper"
"ProjectMapper"..> "ProjectDto"



@enduml