@startuml
skinparam sequenceMessageAlign center
title LIST ALL PROJECTS THE USER IS ALLOCATED AS AUTHENTICATED
legend top
US016 - As Authenticated User, I want to get a list of all projects I'm currently allocated to.
end legend
autonumber
actor User
participant ":ListProjectInAccountUI" as ui
participant ":ListProjectsInAccountController" as controller
participant ":Company" as company
participant ":AccountInProjectContainer" as aipc
participant ":AccountInProject" as aip
participant "projects: List<Project>" as list
participant ":ManagerListProjectsMapper" as pm
participant "managerListProjectDTO: List<ProjectDTO>" as listDTO
participant "managerListProjectDTO:ProjectDTO" as DTO
activate User
User -> ui: lists all projects of a given project
activate ui
ui --> User: request data (email)
User -> ui: types requested data
ui -> controller: listProjectsInAccount(email,emailUser)
activate controller
controller -> company: validateUser(emailUser)
activate company
ref over company: validateUser_sequenceDiagram
company -->> controller: true
deactivate company
controller -> company: listProjectsByAccount(email)
activate company
company -> aipc: listProjectsByAccount(email)
activate aipc
create list
aipc --> list :create()
loop for each AccountInProject in AccountInProjectContainer
aipc -> aip : getProjectByAccount(email)
activate aip
aip --> aipc : project
deactivate aip
aipc -> list : add(project)
activate list
deactivate list
end loop
aipc --> company : projects
deactivate aipc
company --> controller: projects
deactivate company
controller -> pm: getListOfProjectsDTO(projects)
activate pm
create listDTO
pm --> listDTO: create ()
loop for each project in accounts
pm -> list: project = get(i)
list --> pm: project
pm -> pm: projectDTO = projectToDTO(project)
create DTO
pm --> DTO : create()
pm ->listDTO :add(userListProjectDTO)
activate listDTO
end loop
deactivate listDTO
pm --> controller :userListProjectsDTO
deactivate pm
controller -->> ui: userListProjectsDTO
deactivate controller
ui --> User: return list of projects
deactivate ui
@enduml