@startuml
'https://plantuml.com/sequence-diagram

legend top
US016 - As Authenticated User, I want to get a list of all projects I'm currently allocated to.
end legend
skinparam sequenceMessageAlign center
title LIST ALL PROJECTS THE USER IS ALLOCATED AS AUTHENTICATED

class "ListProjectController" {
- company
- projectMapper
+ listProjectByAccount(email)
}
class "Company" {
- accountContainer
+ listProjectByAccount(email)
}
class "AccountContainer"{
- account
- accountInProjectContainer
+ getAccountByEmail(email)

}
class "AccountInProjectContainer"{
- accountInProject
+ listProjectByAccount(account)
}

class "AccountInProject"{
- account
- project
-role
+ accountInProject(account, project, role)
+ getProjectbyAccount(account)
}

class "ProjectMapper"{
+projectsToDTO(projects)
+projectToDTO(project)
}

class "ProjectDTO"{
+projectDTO(project)
}

"ListProjectController"-->"Company"
"Company"-->"AccountContainer"
"AccountContainer"--> "AccountInProjectContainer"
"AccountInProjectContainer"--> "AccountInProject"
"AccountInProjectContainer"--> "ProjectMapper"
"ProjectMapper"..> "ProjectDTO" : create


@enduml