@startuml
skinparam sequenceMessageAlign center
title LIST ALL PROJECTS THE USER IS ALLOCATED AS AUTHENTICATED
legend top
US016 - As Authenticated User, I want to get a list of all projects I'm currently allocated to.
end legend
autonumber
actor User
participant ":ListAccountsInProjectUI" as ui
participant ":ListProjectsInAccountController" as controller
participant ":Company" as company
participant ":AccountContainer" as container

participant "account:Account" as acc
participant ":AccountInProjectContainer" as aipc
participant ":AccountInProject" as aip
participant "Projects: List<Project>" as list
participant ":ProjectMapper" as mapper
participant "projectsDTO: List<ProjectDTO>" as listdto
participant "projectDTO:ProjectDTO" as DTO
participant "profile:Profile" as pf

activate User
User -> ui: Lists all projects the user is allocated to
activate ui
ui -> controller: listProjectByAccount(email)
activate controller
controller -> company: validateUser(email)
activate company

company -> container: validateUser(email)
activate container
container -> acc: validateUser(email)
activate acc
acc -> pf: getProfileByName()
acc-->container : true
deactivate acc
container--> company: true
deactivate container
company --> controller: true
deactivate company
controller -> company: listProjectByAccount(email)
activate company
company -> container : listProjectByAccount(email)
activate container
container -> container : account= getAccountByEmail(email)
container -> aipc : listProjectByAccount(account)
activate aipc

create list
aipc -> list :create()
loop for each AccountInProject in AccountInProjectContainer
aipc -> aip : getProjectByAccount(account)
aip --> aipc : project
aipc -> list : addProject(project)
end loop
aipc --> container : projects
deactivate aipc
container --> company : projects
deactivate container

deactivate container

company --> controller : projects
deactivate company
create mapper
controller -> mapper: projectsToDTO(projects)
deactivate company
activate mapper
create listdto
mapper --> listdto : create ()
loop for each project in projects
mapper -> list: project = get(i)
list --> mapper: project
deactivate aipc
mapper -> mapper : projectDTO = projectToDTO(project)
activate mapper
create DTO
mapper --> DTO : create()
deactivate mapper
mapper -> listdto :add(projectDTO)
end loop
mapper --> controller :projectsDTO
deactivate mapper
controller -->> ui: projectsDTO
deactivate controller
ui -->> User: projectsDTO
deactivate ui
@enduml