@startuml

skinparam sequenceMessageAlign center
title TO REGISTER NEW PROJECT
legend top
US010 - As Manager, I want to register/create a new project.
end legend

class RegisterProjectController {
- service
+ registerProject(DTO, email)
}

class Service {
-company
+registerProject(DTO, email)

}

class Company {
- projectContainer
- accountContainer
+ validateManager(email)
+ registerProject (DTO)
}
class AccountContainer {
+ validateManager(email)
- Accounts
}

class Account {
+ isManager()
- profile
}

class Profile {
-profileName
}

class ProjectContainer {
- projects
+ registerProject(DTO)
}

class ProjectMapper{
+ createProject(DTO)
}

class ProjectDTO{
+ code
+ name
+ customer
+ status
+ startDate
+ endDate
}

class Project{
- code
- name
- customer
- status
- startDate
- endDate

}

RegisterProjectController --> Service
Service "1"-->"1" Company: has
Company "1"-->"1" ProjectContainer: has
Company "1"-->"1" AccountContainer: has
AccountContainer "1"-->"*" Account: contains
ProjectContainer "1"-->"*" Project: contains
Account "1"-->"1" Profile: has
ProjectMapper ..> ProjectDTO
ProjectContainer ..> ProjectMapper
@enduml
