@startuml
'https://plantuml.com/sequence-diagram
legend top
US017 - As Product Owner, I want to create User Story and add it to Product Backlog
end legend
skinparam sequenceMessageAlign center
title To create User Story and add it to Product Backlog

class "CreateUserStoryController" {
- company
+ createUserStory(projectDto,userStoryCreationDto)
}

class "Company" {
- projectContainer
+ createUserStory(projectDto,userStoryCreationDto)
}


class "ProjectContainer" {
- projects
+ createUserStory(projectDto,userStoryCreationDto)
-getProjectByCode(projectCode)
}

class "Project"{
- productBacklog
- sprints
+ createUserStory(userStoryCreationDto)
- hasProjectCode(projectCode)

}
class "Sprint"{
-SprintBackolg
+hasUserStory (userStoryNumber)
}

class "SprintBacklog"{
-userStories
+hasUserStory((userStoryNumber)
}

class "ProductBacklog" {
- userStories
+ createUserStory(userStoryCreationDto,sprints)
- isUserStoryUnique(userStoryNumber)
}
class "UserStory"{
- userStoryNumber
- actor
- userStoryText
- status
- effort
- listOfAcceptanceCriteria
-UserStory(userStoryNumber)
+ createUserStory(userStoryNumber, actor, userStoryText)
- setActor(String actor)
- setUserStoryText(String userStoryText)
+ hasUserStoryNumber(String userStoryNumber)
}


interface "FactoryUserStory" {
+ createUserStory( userStoryNumber,actor, userStoryText)
}
class "UserStoryCreationDto"{
+userStoryNumber
+actor
+userStoryText
}
class "ProjectDto"{
-projectCode
}

"CreateUserStoryController""1"-->"1" "Company"
"Company" "1"--> "1" "ProjectContainer"
"ProjectContainer" "1"-->"*" "Project"
"Project" "1" -->"1" "ProductBacklog"
"Sprint" "*"<.. "Project"
"ProductBacklog" "*" --> "1""FactoryUserStory"
"FactoryUserStory" ..> "UserStory"
"ProjectDto"<.. "ProjectContainer"
"UserStoryCreationDto"<.."UserStoryContainer"
"ProductBacklog" ..> "Sprint"
"Sprint" "1"-->"1" "SprintBacklog"
@enduml