@startuml
skinparam sequenceMessageAlign center
title TO CREATE USER STORY
legend top
US017 - As a Product Owner, I want to create a user story and add it to the Product Backlog.
end legend
autonumber
actor "Product Owner" as product
participant ":CreateUserStoryUI" as ui
participant ":CreateUserStoryController" as controller
participant ":Company" as company
participant ":ProjectContainer" as container
participant ":Project" as project
participant ":Sprint" as sprint
participant ":SprintBacklog" as sprintBacklog
participant ":ProductBacklog" as backlog
participant ":FactoryUserStory" as factory
participant "userStory:UserStory" as userStory


activate product
product -> ui : requests list of projects
activate ui
ref over ui: US016: list all projects the user is allocated as authenticated
ui --> product: shows list of projects
product -> ui : select project
deactivate ui
product -> ui : creates User Story
activate ui
ui --> product: requests data (US_number, actor, US_text, priority)
product -> ui: enters User Story data
ui -> controller: createUserStory(projectDto,userStoryCreationDto)
activate controller
controller -> company: createUserStory(projectDto,userStoryCreationDto)
activate company
company -> container: createUserStory((projectDto,userStoryCreationDto)
activate container
container -> project: createUserStory(userStoryCreationDto)
activate project
project ->sprint:hasUserStory (userStoryNumber)
activate sprint
sprint -> sprintBacklog: hasUserStory (userStoryNumber)
activate sprintBacklog
sprintBacklog --> sprint: false
deactivate sprintBacklog
sprint --> project: false
deactivate sprint
project ->backlog: createUserStory(userStoryCreationDto)
activate backlog
backlog -> factory: createUserStory( userStoryNumber,userStoryText, actor)
activate factory
create userStory
factory -> userStory
factory --> backlog: true
deactivate factory
backlog --> project: true
deactivate backlog
project --> container: true
deactivate project
container --> company: true
deactivate container
company --> controller: true
deactivate company
controller --> ui: true
deactivate controller
ui --> product: "informs Operation Success"
deactivate ui
deactivate product
@enduml
