@startuml
skinparam sequenceMessageAlign center
title TO CREATE USER STORY
legend top
US017 - As a Product Owner, I want to create a user story and add it to the Product Backlog.
end legend
autonumber
actor "Product Owner" as product
participant ":CreateUserStoryUI" as ui
participant ":CreateUSController" as controller
participant ":UsService" as service
participant ":FactoryUserStory" as factory
participant "userStory:UserStory" as userStory
participant ":UsRepository" as usrep
participant ":ProjectService" as pservice
participant ":ProductBacklog" as pbacklog



activate product
product -> ui : requests list of projects
activate ui
ref over ui: US016: list all projects the user is allocated as authenticated
ui --> product: shows list of projects
product -> ui : select project
deactivate ui
product -> ui : creates User Story
activate ui
ui --> product: requests data (US_number, actor, US_text, priority)
product -> ui: enters User Story data
ui -> controller: createUS(projectDto, userStoryCreationDto)
activate controller
controller -> service:createUs(userStoryCreationDto, projectCode)
activate service

service -> factory: createUserStory(userStoryCreationDto, projectCode)
activate factory
create userStory
factory -> userStory
factory -> service: userStory
deactivate factory
service -> usrep: add(userStory)
activate usrep
deactivate usrep
service --> controller: usId
deactivate service
controller -> pservice: addUsToProductBacklog(usId, projectCode, priority)
activate pservice
pservice -> pbacklog : addUsToProductBacklog(priority, usId)
activate pbacklog
pbacklog --> pservice : true
deactivate pbacklog
pservice --> controller : true
deactivate pservice
controller --> ui: true
deactivate controller
ui --> product: "informs Operation Success"
deactivate ui
deactivate product
@enduml