@startuml
'https://plantuml.com/sequence-diagram
legend top
US017 - As Product Owner, I want to create User Story and add it to Product Backlog
end legend
skinparam sequenceMessageAlign center
title To create User Story and add it to Product Backlog


class "CreateUsController" {
- usService
- projectService
+ createUs(projectDto, userStoryCreationDto)
}

class "UsService" {
- factoryUserStory
- usRepository
- userStoryMapper
+ createUs(userStoryCreationDto, projectCode)
+ deleteUs(usId)
}

class "UsRepository" {
-userStories
+add(userStory)
}

class "ProjectService"{
-productBacklog
+ addUsToProductBacklog(usId, projectCode, priority)
}

class "ProductBacklog" {
-priority
-usId
+addUserStory(priority,usId)
}

class "UserStory"{
- usId
- usNumber
- actor
- usText
- status
- acceptanceCriteria
-UserStory(usId)
+setStatus(status)
+setUsText(usText)
+setUsNumber(usNumber)
+setActor(actor)
+has(usNumber)
+setValidUserStory(usNumber, usText, actor)
}

interface "IFactoryUserStory" {
+ createUserStory(userStoryCreationDto, projectCode)
}


class "UserStoryCreationDto"{
+userStoryNumber
+actor
+userStoryText
+getPriority()
}

class "ProjectDto"{
+projectCode
+getProjectCode()
}

"CreateUsController""1"-->"1" "UsService"
"UsService" "1"-->"1" "IFactoryUserStory"
"UserStoryCreationDto" <.. "CreateUsController"
"UserStoryCreationDto" <. "UsService"
"UserStoryCreationDto" <. "IFactoryUserStory"
"IFactoryUserStory" "1"..>"*" "UserStory"
"ProjectDto" <. "UsService"
"UsService" "1"->"1" "UsRepository"
"CreateUsController" "1"->"1" "ProjectService"
"CreateUsController" .>"ProjectDto"
"ProjectService" "1"->"1" "ProductBacklog"

@enduml