@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam sequenceMessageAlign center
title TO ADD BUSINESS SECTOR
legend top
US008 - As Administrator, I want to add a business sector.
end legend

actor Administrator as a
participant ":AddBusinessSectorUI" as absui
participant ":AddBusinessSectorController" as absc
participant ":Service" as s
participant ":Company" as c
participant ":AccountContainer" as ac
participant "account:Account" as acc
participant ":BusinessSectorContainer" as bsc
participant "businessSector:BusinessSector" as bs

activate a
a -> absui: starts adding new business sector
activate absui
a <-- absui: requests data (name)
a -> absui: types requested data
absui -> absc: addBusinessSector(name, email)
activate absc
absc -> s: addBusinessSector(name, email)
activate s
s -> c: validateAdministrator(email)
activate c
c -> ac: validateAdministrator(email)
activate ac
ac -> ac: account = getAccountByEmail(email)
ac -> acc: validateAdministrator(email)
activate acc
ac <-- acc: true
deactivate acc
c <-- ac: true
deactivate ac
s <-- c: true
deactivate c
s -> c: addBusinessSector(name)
activate c
c -> bsc: addBusinessSector(name)
activate bsc
create bs
bsc -> bs: create(name)
bsc -> bsc: add(businessSector)
c <-- bsc: true
deactivate bsc
s <-- c: true
deactivate c
absc <-- s: true
deactivate s
absui <-- absc: true
deactivate absc
a <-- absui: informs operation success
deactivate absui

@enduml