@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam sequenceMessageAlign center
title TO ADD BUSINESS SECTOR
legend top
US008 - As Administrator, I want to add a business sector.
end legend

actor Administrator as a
participant ":AddBusinessSectorUI" as absui
participant ":AddBusinessSectorController" as absc
participant ":Company" as c
participant ":BusinessSectorContainer" as bsc
participant "businessSector:BusinessSector" as bs

activate a
a -> absui: starts adding new business sector
activate absui
a <-- absui: requests data (name)
a -> absui: types requested data
absui -> absc: addBusinessSector(name)
activate absc
absc -> c: addBusinessSector(name)
activate c
c -> bsc: addBusinessSector(name)
activate bsc
create bs
bsc -> bs: create(name)
bsc -> bsc: add(businessSector)
bsc --> bsc: true
c <-- bsc: true
deactivate bsc
absc <-- c: true
deactivate c
absui <-- absc: true
deactivate absc
a <-- absui: informs operation success
deactivate absui

@enduml