@startuml
'https://plantuml.com/class-diagram

class AddBusinessSectorController {
-company
+addBusinessSector(name)
}

class Company {
-businessSectorContainer
+addBusinessSector(name)
}

class BusinessSectorContainer {
-businessSectors
+addBusinessSector(name)
-doesBusinessSectorExist(businessSector)
}

class BusinessSector {
-name
+BusinessSector(name)
}

AddBusinessSectorController --> Company
Company --> BusinessSectorContainer
BusinessSectorContainer --> BusinessSector

@enduml