@startuml

title TO LIST ALL SPRINTS FROM A PROJECT
skinparam sequenceMessageAlign center

class SprintWebController {
-sprintListService
-sprintDtoAssembler
+listSprintsFromProject(codeStringDto)
}

class SprintListService {
-iSprintRepository
-sprintDtoAssembler
+listSprintsFromProject(codeVoDto)
}

interface ISprintRepository {
+findByProjectCode(code)
}

class SprintRepository {
-sprints
+findByProjectCode(code)
}

class SprintDtoAssembler {
+sprintToValueObjectsDto(sprint)
+convertToPrimitiveTypes(sprintValueObjectsDto)
}

class SprintValueObjectsDto {
-number
-status
-startDate
-endDate
+getNumber()
+getStatus()
+getStartDate()
+getEndDate()
}

class SprintPrimitiveTypesDto {
-number
-status
-startDate
-endDate
+getNumber()
+getStatus()
+getStartDate()
+getEndDate()
}

class Sprint {
-sprintNumber
-sprintStatus
-period
+getSprintNumber()
+getStatus()
+getStartDate()
+getEndDate()
}

SprintWebController <.. SprintListService: is injected
SprintListService <.. ISprintRepository: is injected
SprintRepository ..|> ISprintRepository: implements
SprintListService ..> Sprint: uses
SprintDtoAssembler ..> SprintListService: is injected
SprintDtoAssembler ..> SprintWebController: is injected
SprintDtoAssembler ..> Sprint: uses
SprintValueObjectsDto <.. SprintDtoAssembler: uses
SprintPrimitiveTypesDto <.. SprintDtoAssembler: uses
Sprint "*" <-down- "1" SprintRepository: has

@enduml