@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam sequenceMessageAlign center
title MANAGER AUTHORIZATION
legend top
As a Manager, I want authorization
end legend
autonumber
actor Manager
participant ":SomeUI" as ui
participant ":SomeController" as controller
participant ":Company" as company
participant ":AccountContainer" as ac
participant "account:Account" as a
participant "profile:Profile" as p

activate Manager
Manager -> ui: doSomething
activate ui
ui -> controller: doSomething(email)
activate controller
controller -> company: validateManager(email)
activate company
company -> ac: validateManager(email)
activate ac
ac -> a: checkAccountFromEmail(email)
activate a
a-->>ac: true
ac -> a: isManager()
a-> p: isManager()
activate p
p-->> a:true
deactivate p
a -->> ac: true
deactivate a
ac -->> company: true
deactivate ac
company-->> controller: true
@enduml