@startuml

skinparam sequenceMessageAlign center
title AS A ADMINISTRATOR I WANT AUTHORIZATION

class "Controller"{
-company
+validateAdministrator(email)
}

class "Company"{
-accountContainer
+validateAdministrator(email)
}

class "AccountContainer"{
-accounts
+validateAdministrator(email)
}

class "Account"{
-email
-profile
+checkAccountFromEmail(email)
+isAdministrator()
}

class "Profile"{
-profileName
+isAdministrator()
}
"Controller" --> "Company"
"Company" "1"-->"1" "AccountContainer": has
"AccountContainer" --> "Account"
"Account" --> "Profile"
@enduml