@startuml

skinparam sequenceMessageAlign center
title AS AN USER I WANT AUTHORIZATION

class "Controller"{
-company
+validateUser(email)
}

class "Company"{
-accountContainer
+validateUser(email)
}

class "AccountContainer"{
-accounts
+validateUser(email)
}

class "Account"{
-email
-profile
+checkAccountFromEmail(email)
+isUser()
}

class "Profile"{
-profileName
+isUser()
}
"Controller" --> "Company"
"Company" "1"-->"1" "AccountContainer": has
"AccountContainer" --> "Account"
"Account" --> "Profile"
@enduml