@startuml
skinparam sequenceMessageAlign center
title TO VIEW THE SCRUM BOARD OF SPRINT.
legend top
US022 - As Team Member, I want to view the Scrum Board of current sprint.
end legend
autonumber
actor "Team Member" as member
participant ":ViewScrumBoardUI" as ui
participant ":ViewScrumBoardController" as controller
participant ":Company" as company
participant ":ProjectContainer" as projectContainer
participant ":Project" as project
participant ":Sprint" as sprint
participant ":SprintBacklog" as backlog
participant ":UserStoryDtoListAssembler" as dto


activate member
activate ui
member -> ui : requests list of projects
ref over ui: US016: list all projects the user is allocated as authenticated
ui --> member : show list of projects
member -> ui : select project
deactivate ui
member -> ui : requests to view the Scrum Board of current sprint
activate ui
"ui" -> controller : getScrumBoard(projectDto, date, iFactoryUserStory)
activate controller
"controller" -> company : getScrumBoard(projectDto, date, iFactoryUserStory)
activate company
"company" -> projectContainer : getScrumBoard(projectDto, date, iFactoryUserStory)
activate projectContainer
"projectContainer" -> project: getSprintBacklogByDate(date, iFactoryUserStory)
activate project
"project" -> sprint : getSprintBacklogCopy(iFactoryUserStory)
activate sprint
"sprint"-> backlog: getUserStoriesCopy(iFactoryUserStory)
activate backlog
"backlog"-> backlog : getUserStoriesCopy(iFactoryUserStory)
"backlog"-> sprint : sprintBacklog
deactivate backlog
"sprint" -> project : sprintBacklog
deactivate sprint
project -> projectContainer : sprintBacklog
deactivate project
projectContainer -> company : sprintBacklog
deactivate projectContainer
company-> controller : sprintBacklog
deactivate company
controller-> dto : backlogToDto(sprintBacklog, iFactoryUserStory)
activate dto
"dto" ->backlog: getUserStories()
activate backlog
"backlog" -> dto: userStories
deactivate backlog

ref over dto: To create a user story DTO

dto --> controller : userStoryDtoList
deactivate dto
controller -> ui : userStoryDtoList
deactivate controller
ui -> member : shows Scrum Board of current sprint

@enduml