@startuml
skinparam sequenceMessageAlign center
title TO VIEW THE SCRUM BOARD OF SPRINT.
legend top
US022 - As Team Member, I want to view the Scrum Board of current sprint.
end legend
autonumber
actor "Team Member" as member
participant ":UserStoriesInSprintUI" as ui
participant ":UserStoriesInSprintController" as controller
participant ":UserStoriesInSprintService" as service
participant ":SprintRepository" as repository

participant ":UserStoryRepository" as usRepository
participant ":UserStoryMapper" as dto

activate member
activate ui
member -> ui : requests to view the Scrum Board of current sprint

ui --> member : requests data (projectCode, date)
member -> ui : enters requested data

"ui" -> controller : getScrumBoard(projectCode, date)
activate controller
"controller" -> service : getScrumBoard(projectCode, date)
activate service

"service" -> repository : getScrumBoard(projectCode, date)
activate repository
"repository"--> service : sprints
deactivate repository
"service" -> usRepository : getScrumBoard(projectCode, date)
deactivate repository
activate usRepository

usRepository -->"service"   : userStories
deactivate usRepository
deactivate repository

service-> dto : userStoryToDtoList(userStories)
deactivate service
activate dto

activate repository

deactivate repository

ref over dto: To create a user story DTO

dto --> controller : userStoryDto
deactivate dto
controller --> ui : userStoryDto
deactivate controller
ui --> member : shows Scrum Board of current sprint
deactivate ui

@enduml