@startuml

skinparam sequenceMessageAlign center
title TO VIEW THE SCRUM BOARD OF SPRINT
legend top
US022 - As Team Member, I want to view the Scrum Board of current sprint.
end legend

class ViewScrumBoardController
class Company
class ProjectContainer
class Project
class Sprint
class SprintBacklog
class ProjectDto
interface FactoryUserStory
class UserStory
class UserStoryDtoListAssembler
class UserStoryDtoMapper
class UserStoryDto

class ViewScrumBoardController {
-company
+getScrumBoard(projectDto, date)
}

class Company {
-projectContainer
+getScrumBoard(projectDto, date)
}

class ProjectContainer {
-projects
-getProjectByCode(projectCode)
+getScrumBoard(date)
}

class Project {
-projectCode
-sprints
+hasProjectCode(projectCode)
+getSprintByDate(date)
+getScrumBoard()
}

class Sprint {
-sprintBacklog
-period
+getSprintBacklogCopy(factoryUserStory)
+getPeriodByDate(date)
}

class Period {
-startDate
-endDate
+isDateWithinPeriod(date)
+isDateEqualOrGreaterThanStartDate(date)
+isDateEqualOrLowerThanEndDate(date)
}

class SprintBacklog {
-userStories
+getUserStoriesCopy(factoryUserStory)
}

class ProjectDto {
+projectCode
}

interface FactoryUserStory {
+createUserStory(userStoryNumber, actor, userStoryText)
}

class UserStory {
-userStoryNumber
-userStoryText
-status
-actor
+getUsNumber()
+getUsStatus()
+setUsStatus()
+getUsText()
+getActor()
}

class UserStoryDto {
+userStoryNumber
+userStoryText
+status
}

class UserStoryDtoMapper {
+userStoriesToDto(userStory)
}

class UserStoryDtoListAssembler {
+backlogToDto(sprintBacklog)
}

"ViewScrumBoardController" --> "Company"
"Company" "1" --> "1" "ProjectContainer": contains
"ProjectContainer" "1" --> "*" "Project": contains
"Project" "1" --> "*" "Sprint": has
"Sprint" "1" --> "1" "SprintBacklog": has
"Sprint" "1" --> "1" "Period": has
"SprintBacklog" --> "FactoryUserStory"
"SprintBacklog" "1" --> "*" "UserStory": has
"FactoryUserStory" .--> "UserStory"
"ProjectContainer" .--> "ProjectDto": accesses
"ViewScrumBoardController" .--> "UserStoryDtoListAssembler"
"UserStoryDtoListAssembler" .--> "UserStoryDtoMapper"
"UserStoryDtoMapper" .--> "UserStoryDto": instantiates
"UserStoryDtoMapper" .--> "UserStory"

@enduml