@startuml

class "ListAccountUI"{
}
class "ListAccountController" {
-Company
+ac=getAccountContainer()
+copy=getCopyAccountList()
}
class "Company"{
+ac=getAccountContainer()

}
class "ac:AccountContainer"{
+copy=getCopyAccountList()
}
class "a:Account"{}
hide "ListAccountUI" circle
hide "ListAccountController" circle
hide "Company" circle
hide "ac:AccountContainer" circle
hide "a:Account" circle

"ListAccountUI" ..> "ListAccountController"
"ListAccountController" ..> "Company"
"ListAccountController" ..> "ac:AccountContainer"

@enduml