@startuml

skinparam sequenceMessageAlign center
actor Administrator
participant ListAccountUI as ui
participant ":ListAccountController" as controller
participant ":Company" as company
participant "ac:AccountContainer" as acontainer
participant "a:Account" as aaccount

activate Administrator
Administrator -> ui: 1. Lists all accounts
activate ui
ui -> controller: 1.1 ListAllAccount()
activate controller
controller -> company: 1.1.1 ac=getAccountContainer()
activate company
deactivate company
controller-> acontainer: 1.1.2 copy=getCopyAccountList()
activate acontainer
deactivate acontainer
controller --> ui: ok
deactivate controller
ui --> Administrator: ok

@enduml