@startuml

class Account{
-email
-status
+getEmail()
+getStatus()

}
class "AccountListController" {
+createInfo(email, status)
}
class AccountList{
+addToList(accountInfo)
+accountInfo(email, status)
}

"AccountList" "1" --> "*" Account: lists
"AccountListController" "1" --> "*" Account: gets

hide "Account" circle
hide "AccountList" circle
hide "AccountListController" circle

@enduml