@startuml

skinparam sequenceMessageAlign center
title TO LIST ALL ACCOUNTS
legend top
US004 - As Administrator, I want to get a list of all user accounts and their status.
end legend

class "ListAccountController" {
-company
+listAllAccounts()
}

class "Company"{
-accountContainer
+listAllAccounts()

}
class "AccountContainer"{
-accounts
+listAllAccounts()
}

"ListAccountController" ..> "Company"
"Company" "1"-->"1" "AccountContainer": has

@enduml