@startuml
skinparam sequenceMessageAlign center
title TO LIST ALL ACCOUNTS
legend top
US004 - As Administrator, I want to get a list of all user accounts and their status.
end legend
autonumber
actor Administrator
participant ":ListAccountUI" as ui
participant ":ListAccountController" as controller
participant ":Company" as company
participant "accountContainer:AccountContainer" as container

activate Administrator
Administrator -> ui: Lists all accounts
activate ui
ui -> controller: listAllAccounts()
activate controller
controller -> company: accountContainer = getAccountContainer()
activate company
create container
company -->> container: create
deactivate company
controller -> container: getAccounts()
activate container
deactivate container
controller -->> ui: return accounts
deactivate controller
ui -->>Administrator: return accounts
deactivate ui

@enduml