@startuml

skinparam sequenceMessageAlign center
actor "Administrator"
participant ":AccountListUI" as ui
participant ":AccountListController" as cal
participant ":Repository" as rp


activate "Administrator"
"Administrator" -> ui: 1: request list of all accounts
activate ui
ui -> cal: 1.1: getListAllAccounts()
activate cal
cal -> rp: 1.1.1: getListAllAccounts()
activate rp
rp --> cal :returns list of all accounts
deactivate rp
cal --> ui :returns list of all accounts
deactivate cal
ui --> "Administrator": returns list of all accounts
deactivate ui
@enduml