@startuml
skinparam sequenceMessageAlign center
title LIST ALL PROJECTS THE USER IS ALLOCATED AS AUTHENTICATED
legend top
US016 - As Authenticated User, I want to get a list of all projects I'm currently allocated to.
end legend
autonumber
actor User
participant ":ListAccountsInProjectUI" as ui
participant ":ListAccountsInProjectController" as controller
participant ":Company" as company
participant ":AccountContainer" as container
participant ":AccountInProjectContainer" as aipc
participant ":AccountInProject" as aip
participant "listProj: List<Project>" as list
participant ":ProjectMapper" as mapper
participant "projectsListDTO: List<ProjectDTO>" as listdto
participant "projectDTO:projectDTO" as DTO
participant "account:Account"
participant "project:Project"

activate User
User -> ui: lists all projects the user is allocated to
activate ui
ui -> controller: listProjectByAccount(email)
activate controller
controller -> company: listProjectByAccount(email)
activate company
company -> container: listProjectByAccount(email)
deactivate company
activate container
container ->container: account= getAccountByEmail(email)
container -> aipc: listProjectByAccount(account)
create list
aipc -> list :create()
loop for each AccountInProject in AccountInProjectContainer
aipc -> aip : getProjectByAccount(account)
aip --> aipc : project
aipc -> list : addProject(proj)
end loop
activate aipc
aipc --> container : projectsList
container--> company : projectsList
deactivate container
activate company
company --> controller : projectsList
deactivate company
controller -> mapper: projectsListToDTO(projectsList)
activate mapper
create listdto
mapper --> listdto : create ()
loop for each project in projectsList
mapper -> list: project = get(i)
list --> mapper: project
deactivate aipc
mapper -> mapper : projectDTO = projectToDTO(project)
create DTO
mapper --> DTO : create()
mapper ->listdto :add(projectDTO)
end loop
mapper --> controller :projectsListDTO
deactivate mapper
controller -->> ui: projectsListDTO
deactivate controller
ui -->> User: projectsListDTO
deactivate ui
@enduml