@startuml
'https://plantuml.com/sequence-diagram

legend top
US016 - As Authenticated User, I want to get a list of all projects I'm currently allocated to.
end legend
skinparam sequenceMessageAlign center
title LIST ALL PROJECTS THE USER IS ALLOCATED AS AUTHENTICATED

class "ListProjectController" {
- company
+ listProjectsByAccount(e-mail)
}
class "Company" {
- projectContainer
+ getProjectsByAccount(email)
}
class "ProjectContainer" {

}
class "Projects" {

}
class "Account" {

}

@enduml