@startuml
skinparam sequenceMessageAlign center
title LIST ALL PROJECTS THE USER IS ALLOCATED AS AUTHENTICATED
legend top
US016 - As Authenticated User, I want to get a list of all projects I'm currently allocated to.
end legend
autonumber
actor User
participant ":ListProjectUI" as ui
participant ":ListProjectController" as controller
participant ":Company" as company
participant ":AccountContainer" as container
participant ":AccountInProjectContainer" as aipc
participant ":AccountInProject" as aip
participant "List<Project>"
participant "proj:Project"
participant "listProj: List<Project>" as list
participant ":ProjectMapper" as mapper
participant "projectDTO:projectDTO" as DTO
participant "listProjectByAccountDTO: List<ProjectDTO>" as listdto


activate User
User -> ui: lists all projects the user is allocated to
activate ui
ui -> controller: listProjectByAccount(email)
activate controller
controller -> company: listProjectByAccount(email)
activate company
company -> container: listProjectByAccount(email)
deactivate company
activate container
container ->container: account= getAccountByEmail(email)
container -> aipc: listProjectByAccount(account)
create list
aipc -> list :create()
loop
aipc -> aip : getProjectByAccount(account)
aip --> aipc : project
aipc -> list : addProject(proj)
end loop
activate aipc
aipc --> container : listProjectByAccount
container--> company : listProjectByAccount
deactivate container
activate company
company --> controller : listProjectByAccount
deactivate company
controller -> mapper: toDTO(listProjectByAccount)
activate mapper
create listdto
mapper --> listdto : create ()
loop for
mapper -> container: project = get(i)
activate container
container --> mapper: project
deactivate container
mapper -> mapper : projectDTO = toDTO (project)
create DTO
mapper --> DTO : create()
mapper ->listdto :add(projectDTO)
end loop
mapper --> controller :listProjectByAccountDTO
deactivate mapper
controller -->> ui: listProjectByAccountDTO
deactivate controller
ui -->> User: listProjectByAccountDTO
deactivate ui
@enduml