@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO SEARCH ACCOUNT BY E-MAIL
actor Administrator
autonumber
Administrator -> ":System": Searches account by e-mail
note left
Account is authenticated.
":System" grants access.
end note
":System" --> Administrator: returns account matching
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO SEARCH ACCOUNT BY PROFILE
actor Administrator
autonumber
Administrator -> ":System": Searches account by profile
note left
Account is authenticated.
":System" grants access.
end note
":System" --> Administrator: returns list of accounts
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO MANAGE PROJECT
actor "Project Manager" as PM
autonumber
PM -> ":System": Edits project info
note left
Account is authenticated.
":System" grants access.
end note
PM <-- ":System": project info updated
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO SEARCH PROJECT BY MANAGER
actor "Manager"
autonumber
"Manager" -> ":System": Searches project by (code, name, etc.)
note left
Account is authenticated.
":System" grants access.
end note
"Manager" <-- ":System": lists all projects matching
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO SEARCH PROJECT BY USER
actor "User in Project" as UIP
autonumber
UIP -> ":System": Searches project by (code, name, etc.)
note left
Account is authenticated.
":System" grants access.
end note
UIP <-- ":System": lists projects User is / was enrolled
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO CREATE SPRINT
actor "User in Project" as UIP
autonumber
UIP -> ":System": Requests product backlog data
note left
Account is authenticated.
":System" grants access.
end note
UIP <-- ":System": returns US
UIP -> ":System": Defines US for sprint
UIP <-- ":System": new sprint created
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO GROOM USER STORY
actor "Product Owner" as PO
"PO" -> ":System": Requests product backlog data
note left
Account is authenticated.
":System" grants access.
end note
PO <-- ":System": returns US
PO -> ":System": Decomposes US
PO <-- ":System": US replaced
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO REVIEW SPRINT
actor "Product Owner" as PO
"PO" -> ":System": Accesses all sprint's US
note left
Account is authenticated.
":System" grants access.
end note
PO <-- ":System": returns US
PO -> ":System": Returns not finished US to product backlog
PO <-- ":System": US remains in product backlog
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO CREATE TASK FOR USER STORY
actor "User in Project" as UIP
"UIP" -> ":System": Creates task related to US
note left
Account is authenticated.
":System" grants access.
end note
UIP <-- ":System": requests task data
UIP -> ":System": Enters task data
UIP <-- ":System": new task created
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO UPDATE TASK IN USER STORY
actor "User in Project" as UIP
"UIP" -> ":System": Updates info about task
note left
Account is authenticated.
":System" grants access.
end note
UIP <-- ":System": requests update description
UIP -> ":System": Enters data
UIP <-- ":System": task updated
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO FINISH TASK IN USER STORY
actor "User in Project" as UIP
"UIP" -> ":System": Registers task finished during sprint
note left
Account is authenticated.
":System" grants access.
end note
UIP <-- ":System": returns unfinished US to product backlog
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO ALLOCATE RESOURCE IN PROJECT
actor "Manager"
"Manager" -> ":System": Assigns resource to project
note left
Account is authenticated.
":System" grants access.
end note
"Manager" <-- ":System": requests data (startingDate, endingDate,\n costPerHour, percentAllocation)
"Manager" -> ":System": Enters data
"Manager" <-- ":System": resource added to project
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO GENERATE ALLOCATION REPORT BY MANAGER
actor "Manager"
"Manager" -> ":System": Requests allocation report of \n any member of any project
note left
Account is authenticated.
":System" grants access.
end note
"Manager" <-- ":System": generates allocation report
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO GENERATE ALLOCATION REPORT BY \n PROJECT MANAGER, PRODUCT OWNER OR SCRUM MASTER
actor "PM, PO or SM" as PPS
"PPS" -> ":System": Requests allocation report of any member \n of projects he / she / they are involved in
note left
Account is authenticated.
":System" grants access.
end note
PPS <-- ":System": generates allocation report
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO GENERATE ALLOCATION REPORT BY TEAM MEMBER
actor "Team Member" as TM
"TM" -> ":System": Requests personal allocation report \n of projects he / she / they are involved in
note left
Account is authenticated.
":System" grants access.
end note
TM <-- ":System": generates allocation report
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO GENERATE KPI REPORT BY MANAGER
actor "Manager"
autonumber
"Manager" -> ":System": Requests KPI report of any project
note left
Account is authenticated.
":System" grants access.
end note
"Manager" <-- ":System": reports CPI and SPO in chosen format
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO GENERATE KPI REPORT BY PROJECT MANAGER OR PRODUCT OWNER
actor "PM or PO" as PP
autonumber
PP -> ":System": Requests KPI report of project \n he/she/they are involved in
note left
Account is authenticated.
":System" grants access.
end note
PP <-- ":System": reports CPI and SPO in chosen format
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO KEEP RECORD OF SCRUM CEREMONY
actor "User in Project" as UIP
autonumber
UIP -> ":System": Begins ceremony
note left
Account is authenticated.
":System" grants access.
end note
UIP <-- ":System": starts recording
UIP -> ":System": Finishes ceremony
UIP <-- ":System": stops recording / keeps record
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO SEARCH All PROJECTS BY MANAGER
actor "Manager"
autonumber
"Manager" -> ":System": List all projects
note left
Account is authenticated.
":System" grants access.
end note
"Manager" <-- ":System": ShowListAllProjects
@enduml

@startuml
legend top
US009 - "As Administrator, I want to add a customer."
end legend
skinparam sequenceMessageAlign center
title TO ADD A CUSTOMER
actor "Administrator"
autonumber
Administrator -> ":System": starts adding new customer
note left
Account is authenticated.
":System" grants access.
end note
Administrator <-- ":System": requests data (taxIdNumber, name)
Administrator-> ":System": enters requested data
Administrator <-- ":System":informs operation success
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title AS A MANAGER, TO LIST ALL HUMAN RESOURCES IN A PROJECT
actor "Manager"
autonumber
"Manager" -> ":System": lists all accounts of a given project
note left
Account is authenticated.
":System" grants access.
end note
"Manager" <-- ":System": returns list of accounts
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO LIST ALL PROJECTS THE USER IS ALLOCATED AS AUTHENTICATED
actor "User"
autonumber
"Team Member" -> ":System": lists all projects the user is allocated to
note left
Account is authenticated.
":System" grants access.
end note
"User" <-- ":System": shows list of all projects the user is allocated
@enduml

@startuml
legend top
US0 - .
end legend
skinparam sequenceMessageAlign center
title TO ESTIMATE THE EFFORT OF A USER STORY IN A SPRINT, DURING THE SPRINT PLANNING CEREMONY.
actor "Team Member"
autonumber
"Team Member" -> ":System": requests list of projects
note left
Account is authenticated.
":System" grants access.
end note
note right
Team Member requests to see all
projects and select one (US016).
end note
"Team Member" <-- ":System": requests data
"Team Member" -> ":System": requests list of user stories
note right
Team Member requests to see all
user stories and select one (US022).
end note
"Team Member" <-- ":System": requests data
"Team Member" -> ":System": selects data and estimate user story effort
"Team Member" <-- ":System": shows success message
@enduml
