
@startuml

/'autonumber'/
actor Administrator
participant ":ChangeProfileUI" as ui
participant ":ChangeProfileController" as Controller
participant ":Repository" as repository
participant "account :Account" as account

activate Administrator
Administrator -> ui: 1. changes account profile
activate ui
Administrator <-- ui: 1.1. requests data (e-mail, profile)
deactivate ui
Administrator -> ui: 2.  enters account data
activate ui
ui -> Controller: 2.1. changeProfile(e-mail,profile)
activate Controller
Controller -> repository: 2.1.1. changeProfile(e-mail,profile)
activate repository
repository -> repository: 2.1.1.1. isProfileValid(profile)
repository -> repository: 2.1.1.2. isUserValid(e-mail)
activate repository

repository -> repository: 2.1.1.4. account = getAccount(e-mail)
activate repository
repository --> repository: 2.1.1.5. return account
create account
repository -> account: 2.1.1.6. updateProfile(profile)


deactivate ui
ui --> Administrator: 3. informs profile update
deactivate Administrator

/'Controller -> Controller: isUserValid (e-mail)
Controller -> Controller: isProfileValid (profile)

Controller --> account: changeProfile (e-mail, profile)'/

@enduml