@startuml
class ChangeProfileController
class ChangeProfileUI
class Company
class ProfileContainer
class AccountContainer
hide ChangeProfileController circle
hide Company circle
hide Account circle
hide ChangeProfileUI circle
hide Profile circle
hide ProfileContainer circle
hide AccountContainer circle

ChangeProfileUI ..> ChangeProfileController: requests
ChangeProfileController ..> Company
Company "1" -->"*"AccountContainer
Company "1"-->"*" ProfileContainer
AccountContainer "1"-->"*" Account
ProfileContainer "1"-->"*" Profile



class ChangeProfileUI {
}

class ChangeProfileController {
-company
+ChangeProfileController()
+changeProfile(e-mail, profileName)
}

class Company {
-profileContainer
-accountContainer
+Company()
+getProfileContainer()
+getAccountContainer()
/'+doesEmailExist(email)'/
}

class ProfileContainer {
-profileList
+ProfileContainer()
+getProfileByName(profileName)
}

class AccountContainer {
-accountList
+AccountContainer()
+getAccountByEmail(email)
}

class Account{
-name
-email
-phoneNumber
-photo
-profile
-status
+Account(name, email, phoneNumber, photo, status, profile)
+getEmail()
+accountStatus(status)
+updateAccountStatus(status)
+updateAccountProfile(profile)
+setProfile(profile)
}

class Profile{
-profileName
+Profile(profileName)
+getProfileName()
}
@enduml
