@startuml

class ChangeProfileController
class ChangeProfileUI
class Repository
hide ChangeProfileController circle
hide Repository circle
hide Account circle
hide ChangeProfileUI circle


ChangeProfileUI ..> ChangeProfileController: changes

ChangeProfileController ..> Repository


Repository "1" -->"*"Account: validate


class ChangeProfileUI {
}

class ChangeProfileController {
Repository
+changeProfile(e-mail,profile)
}

class Repository {
Account
+isUserValid(e-mail)
+isProfileValid(profile)
}


class Account{
-email
-profile
+ updateProfile (e-mail, profile)
}


@enduml