@startuml


actor Administrator
participant ":ChangeProfileUI" as ui
participant ":ChangeProfileController" as controller
participant ":Company" as company
participant "profileContainer:ProfileContainer" as pcontainer
participant "accountContainer:AccountContainer" as acontainer
participant "account:Account" as account
participant "profile:Profile" as pprofile

skinparam sequenceMessageAlign center
title TO CHANGE PROFILE
legend top
US003 - As Administrator, I want to change the profile of a user account.
end legend
autonumber
activate Administrator
Administrator -> ui:  Changes account profile
activate ui
Administrator <-- ui:  Requests data (e-mail, profileName)
deactivate ui
Administrator -> ui:  Enters account data
activate ui
ui -> controller: changeProfile(e-mail, profileName)
activate controller
controller -> company: profileContainer=getProfileContainer()
activate company
deactivate company
controller -> pcontainer: profile=getProfileByName(profileName)
activate pcontainer
deactivate pcontainer
controller-> company: accountContainer=getAccountContainer()
activate company
deactivate company
controller -> acontainer: account=getAccountByEmail(e-mail)
activate acontainer
deactivate acontainer
controller -> account: setProfile(profile)
activate account
deactivate account
controller -->> ui: account profile updated
deactivate controller
ui -->> Administrator: informs account profile updated


@enduml