@startuml


actor Administrator
participant ":ChangeProfileUI" as ui
participant ":ChangeProfileController" as controller
participant ":Company" as company
participant "profileContainer:ProfileContainer" as pcontainer
participant "accountContainer:AccountContainer" as acontainer
participant "account:Account" as account
participant "profile:Profile" as pprofile

skinparam sequenceMessageAlign center
title TO CHANGE PROFILE
legend top
US003 - As Administrator, I want to change the profile of a user account.
end legend
autonumber
activate Administrator
Administrator -> ui:  Changes account profile
activate ui
Administrator <-- ui:  Requests data (email, profileName)
deactivate ui
Administrator -> ui:  Enters account data
activate ui
ui -> controller: changeProfile(email, profileName)
activate controller
controller -> company: changeProfile(email, profileName)
activate company
company -> pcontainer: getProfileByName(profileName)
activate pcontainer
company <-- pcontainer: profile
deactivate pcontainer
company -> acontainer: getAccountByEmail(email)
activate acontainer
company <-- acontainer: account
deactivate acontainer
company -> account: setProfile(profile)
activate account
deactivate account
controller <-- company: true
deactivate company
controller --> ui: true
deactivate controller
ui -->> Administrator: informs account profile updated


@enduml