
@startuml
'https://plantuml.com/sequence-diagram
/'autonumber'/
actor Administrator
participant ":ChangeProfileUI" as ui
participant ":ChangeProfileController" as Controller
participant ":Company" as company
participant ":AccountList" as userList
participant "account :Account" as account

activate Administrator
Administrator -> ui: 1. starts the change of a user profile
activate ui
Administrator <-- ui: 1.1. requests data
deactivate ui
Administrator -> ui: 2. provides user id (e-mail) and profile
activate ui
ui -> Controller: 2.1. changeProfile(e-mail,profile)
activate Controller
Controller -> company: 2.1.1. changeProfile(e-mail,profile)
activate company
company -> company: 2.1.1.1. isProfileValid(profile)
company -> userList: 2.1.1.2. isUserValid(e-mail)
activate userList
userList --> company: 2.1.1.3. return true
deactivate userList
company -> userList: 2.1.1.4. account = getAccount(e-mail)
activate userList
userList --> company: 2.1.1.5. return account
deactivate userList
create account
company -> account: 2.1.1.6. updateProfile(profile)
company --> Controller: 2.1.2. return true
deactivate company
Controller --> ui: 2.2. return true
deactivate Controller
deactivate ui
ui --> Administrator: 3. informs about operation success
deactivate Administrator

/'Controller -> Controller: isUserValid (e-mail)
Controller -> Controller: isProfileValid (profile)

Controller --> account: changeProfile (e-mail, profile)'/


@enduml