@startuml
'https://plantuml.com/class-diagram
title Generic Class Model
package "Frameworks" {
class Route
interface IUser
class User
}

package "Interface Adpters Layers" {
class Repo
interface IController
class Controller
}

package "Application Services" {
interface IService
class Service
interface IRepo
}

package "Enterprise Business Rules Layer"  {
class Model

Route ..> IController
Controller --|> IController
Controller ..> IService
Repo ..> IUser
User --|> IUser
Service .up.> IRepo
Service --|> IService
Repo --|> IRepo
Service .up.> Model
@enduml