@startuml
skinparam sequenceMessageAlign center
title Process View - Level 1

autonumber

participant "<<Component>> \n <<Container (C4)>> \n G4-FE"
participant "<<Context (C4)>> \n g4 : G4" as be
participant "<<Internal System>> \n  : H2 DB" as db



"<<Component>> \n <<Container (C4)>> \n G4-FE" -> be: asks to associate of a User as the Product Owner/\nTeam Member/Scrum Master of a given project
activate be

be --> "<<Component>> \n <<Container (C4)>> \n G4-FE": requests data
"<<Component>> \n <<Container (C4)>> \n G4-FE" -> be: sends data (code, email, role,\n costPerHour, percentageOfAllocation, startDate, endDate)
[o-> be
be -> db: save
activate db
deactivate db
be --> "<<Component>> \n <<Container (C4)>> \n G4-FE": informs about operation success

@enduml


@startuml
skinparam sequenceMessageAlign center
title Process View - Level 3

autonumber

participant "<<Component>> \n <<Container (C4)>> \n G4-FE" as fe
participant "<<Component>> \n <<Container (C4)>> \n G4-BE" as be
participant "<<Database>> \n DB H2" as db

[o-> fe: asks to associate of a User as the Product Owner/\nTeam Member/Scrum Master of a given project
activate fe
[o<-- fe: requests data
[o-> fe: sends data (code, email, role,\n costPerHour, percentageOfAllocation, startDate, endDate)
activate be

fe -> be: POST / addUserToProject(allocationDto)
be -> db: INSERT resource
activate db
deactivate db
be --> fe: 201/40?
[o<-- fe: Informs operation success
deactivate fe
@enduml
