@startuml
'https://plantuml.com/class-diagram

class Profile{
-profile
+createProfile(profile)
}
class "CreateProfile:Controller" {
+validateProfile(profile)
+saveProfile(profile)
-addProfile(profile)
}

hide Profile circle
hide "CreateProfile:Controller" circle

"CreateProfile:Controller" "1" --> "*" Profile: creates


@enduml