@startuml

actor Administrator
participant ":CreateProfileUI" as cpu
participant ":CreateProfileController" as cpc
participant ":Company" as Company
participant "pc:ProfileContainer" as ProfileContainer
participant "p:Profile" as Profile
activate Administrator
Administrator -> cpu: 1. creates profile
activate cpu
cpu --> Administrator: 1.1 requests data(profileName)
deactivate cpu
Administrator -> cpu: 2. types requested data
activate cpu
cpu -> cpc: 2.1 createProfile(profileName)
activate cpc
cpc -> Company: 2.1.1 pc=getProfileContainer()
activate Company
deactivate Company
cpc -> ProfileContainer: 2.1.2 doesProfileNameExist(profileName)
activate ProfileContainer
deactivate ProfileContainer
create Profile
cpc -> Profile: 2.1.3 p=createProfile(profileName)
deactivate Profile
cpc -> ProfileContainer: 2.1.4 addProfile(p)
activate ProfileContainer
deactivate ProfileContainer
cpc --> cpu: profile created
deactivate cpc
cpu --> Administrator: informs profile created
deactivate cpu


@enduml
