@startuml
'https://plantuml.com/class-diagram

class "Profile"{
-name
+Profile(name)
}

class "CreateProfileController" {
-Repository
+createNewProfile(name)
}

class "CreateProfileUI"{
}

class "Repository"{
-profileList
-accountList
+validateProfile(profile)
+saveProfile(profile)
-addProfile(profile)
}

hide "Profile" circle
hide "CreateProfileController" circle
hide "CreateProfileUI" circle
hide "Repository" circle

"CreateProfileUI" ..>  "CreateProfileController": requests
"CreateProfileController" ..>  "Repository"
"Repository" "1" --> "*" "Profile": creates

@enduml