@startuml

skinparam sequenceMessageAlign center
title TO CREATE NEW PROFILE
legend top
US001 - As Administrator, I want to create user profiles.
end legend
autonumber
actor Administrator
participant ":CreateProfileUI" as cpui
participant ":CreateProfileController" as cpc
participant ":Company" as Company
participant "profileContainer:ProfileContainer" as ProfileContainer
participant "profile:Profile" as Profile
activate Administrator
Administrator -> cpui: creates profile
activate cpui
cpui -->> Administrator: requests data (profileName)
deactivate cpui
Administrator -> cpui: types requested data
activate cpui
cpui -> cpc: createProfile (profileName)
activate cpc
cpc -> Company: createProfile (profileName)
activate Company


Company -->> ProfileContainer: createProfile (profileName)
activate ProfileContainer


create Profile
ProfileContainer -->> Profile: createProfile (name)

ProfileContainer -> ProfileContainer: addProfile(profile)
ProfileContainer -->> Company: true
deactivate ProfileContainer

Company -->> cpc: true
deactivate ProfileContainer
deactivate Company
cpc -->> cpui: true
deactivate cpc
cpui -->> Administrator: informs profile created
deactivate cpui


@enduml
