@startuml


title GET A LIST OF ALL PROJECTS
skinparam sequenceMessageAlign center
legend top
US015 - As a Manager, I want to get a list of all projects
end legend

class "GetListOfProjectsController" {
-company
+getListOfProjects(email)
}

class "Company"{
-projectContainer
-accountContainer
+validateProfileRequired(email, profileNameRequired)
+listAllProjects()
}

class "AccountContainer"{
-accounts
+validateProfileRequired(email, profileNameRequired)
+getAccountByEmail(email)
}

class "Account"{
-email
-profile
+isProfileRequired(profileNameRequired)
}

class Profile{
-profileName
+isProfileRequired(profileNameRequired)
}

class "ProjectContainer"{
-projects
+getProjects()
}

class "Project"{
-projectCode
}

class "ManagerListProjectsMapper"{
+getListOfProjectsDTO(projects)
-getDTOFromProject(project)
}

class "ManagerListProjectsDTO" {
+code
+name
+customer
+status
+projectTypology
+businessSector
}

"GetListOfProjectsController" "1"-->"1" "Company": has
"GetListOfProjectsController" ..> "ManagerListProjectsMapper"
"Company" "1"-->"1" "ProjectContainer": has
"Company" "1"-->"1" "AccountContainer": has
"AccountContainer" "1"-->"*" Account: contains
"ProjectContainer" "1"-->"*" Project: contains
"Account" "*"-->"1" "Profile" : has
"ManagerListProjectsMapper" ..> "ManagerListProjectsDTO": <<instantiate>>

/'Usage relationship'/
/'https://www.ibm.com/docs/en/rational-soft-arch/9.7.0?topic=diagrams-dependency-relationships'/

/'Creation relationship'/
/'https://www.ibm.com/docs/en/rational-soft-arch/9.7.0?topic=diagrams-instantiation-relationships'/
@enduml