@startuml

skinparam sequenceMessageAlign center
title GET A LIST OF ALL PROJECTS
legend top
US015 - As a Manager, I want to get a list of all projects
end legend

class "GetListOfProjectsController" {
-company
-listOfProjectsMapper
+getListOfProjects(email)
}

class "Company"{
-projectContainer
-accountContainer
+validateManager(email)
+listAllProjects()
}

class "AccountContainer"{
-accounts
+validateManager(email)
+getAccountByEmail(email)
}

class "Account"{
-email
-profile
+isManager()
}

class "ProjectContainer"{
-projects
+getProjects()
}

class "Project"{
-projectCode
}

class "ListOfProjectsMapper"{
+add(projectDTO)
+toDTO(project)
}

class "GetProjectDTO" {
+code
+name
+customer
+status
+projectTypology
+businessSector
+createDTO()
}

"GetListOfProjectsController" "1"-->"1" "Company": has
"GetListOfProjectsController" "1"-->"1" "ListOfProjectsMapper": has
"Company" "1"-->"1" "ProjectContainer": has
"Company" "1"-->"1" "AccountContainer": has
"AccountContainer" "1"-->"*" Account: contains
"ProjectContainer" "1"-->"*" Project: contains
"ListOfProjectsMapper" ..> "GetProjectDTO"
@enduml