@startuml

skinparam sequenceMessageAlign center
title GET A LIST OF ALL PROJECTS
legend top
US015 - As a Manager, I want to get a list of all projects.
end legend
autonumber
actor Manager

participant ":GetListOfProjectsUI" as ui
participant ":GetListOfProjectsController" as controller
participant ":Company" as company
participant ":ProjectContainer" as pc
participant "ProjectMapper" as mapper
participant "projectDto: List<ProjectDto>" as list
participant "projectDto:ProjectDto" as dto

activate Manager
Manager -> ui: asks for list of all projects
activate ui
ui --> Manager: requests data (email)
Manager -> ui: types requested data
ui -> controller: getListOfProjects(email)
activate controller
controller -> company: validateProfileRequired(email, profileNameRequired)
activate company
ref over company: validateManager_sequenceDiagram
company -->> controller: true
deactivate company
controller -> company: listAllProjects()
activate company
company -> pc: getProjects()
activate pc
pc --> company: projects
deactivate pc
company --> controller: projects
deactivate company
controller -> mapper: getListOfProjectsDto(projects)
activate mapper
create list
mapper --> list: create ()
loop for each project in projects
create dto
mapper --> dto: create ()
mapper -> list: add(projectDto)
end loop
controller <-- mapper: projectDto
deactivate mapper
ui <-- controller: projectDto
deactivate controller
ui --> Manager: shows list of all projects
deactivate ui

@enduml