@startuml
skinparam sequenceMessageAlign center
title GET A LIST OF ALL PROJECTS
legend top
US015 - As a Manager, I want to get a list of all projects
end legend
autonumber
actor Manager
participant ":GetListOfProjectsUI" as ui
participant ":GetListOfProjectsController" as controller
participant ":Company" as company
participant ":ProjectContainer" as pc
participant "ManagerListProjectsMapper" as mapper
participant "managerListProjectsDTO: List<ProjectsDTO>" as list
participant "managerListProjectsDTO:ManagerListProjectsDTO" as DTO

activate Manager
Manager -> ui: get list of all projects
activate ui
ui -> controller: getListOfProjects(email)
activate controller
controller -> company: validateProfileRequired(email, profileNameRequired)
activate company
ref over company: validateManager_sequenceDiagram
company -->> controller: true
deactivate company
controller -> company: listAllProjects()
activate company
company -> pc: getProjects()
activate pc
pc --> company: projects
deactivate pc
company --> controller: projects
deactivate company
controller -> mapper: getListOfProjectsDTO(projects)
activate mapper
create list
mapper --> list: create ()
loop for each project in projects
create DTO
mapper --> DTO: create ()
mapper -> list: add(managerListProjectsDTO)
end loop
controller <-- mapper: managerListProjectsDTO
deactivate mapper
ui <-- controller: managerListProjectsDTO
deactivate controller
ui --> Manager: show list all projects
deactivate ui
@enduml