@startuml

skinparam sequenceMessageAlign center
title TO VIEW THE SCRUM BOARD OF SPRINT
legend top
US022 - As Team Member, I want to view the Scrum Board of current sprint.
end legend

class ViewScrumBoardController
class Company
class ProjectContainer
class Project
class Sprint
class SprintBacklog
class ProjectDto
interface IFactoryUserStory
class UserStory
class UserStoryDtoListAssembler
class UserStoryMapper
class UserStoryDto

class ViewScrumBoardController {
-company
+getScrumBoard(projectDto, date, iFactoryUserStory)
}

class Company {
-projectContainer
+getScrumBoard(projectCode, date, iFactoryUserStory)
}

class ProjectContainer {
-projects
+getScrumBoard(projectCode, date, iFactoryUserStory)
}

class Project {
-projectCode
-sprints
+hasProjectCode(projectCode)
+getSprintBacklogByDate(date, iFactoryUserStory)
}

class Sprint {
-sprintBacklog
-period
+isDateWithinPeriod(date)
+getSprintBacklogCopy(iFactoryUserStory)
}

class Period {
-startDate
-endDate
+isDateEqualOrGreaterThanStartDate(date)
+isDateEqualOrLowerThanEndDate(date)
}

class SprintBacklog {
-userStories
+getUserStoriesCopy(iFactoryUserStory)
}

class ProjectDto {
+projectCode
+getProjectCode()
}

interface IFactoryUserStory {
+createUserStory(userStoryNumber, userStoryText)
}

class UserStory {
-userStoryNumber
-userStoryText
-status
-actor
+getUserStoryNumber()
+getStatus()
+setStatus()
+getUserStoryText()

}

class UserStoryDto {
+userStoryNumber
+userStoryText
+status
}

class UserStoryMapper {
+userStoriesToDto(userStory)
}

class UserStoryDtoListAssembler {
+backlogToDto(sprintBacklog, iFactoryUserStory)
}

"ViewScrumBoardController" --> "Company"
"Company" "1" --> "1" "ProjectContainer": contains
"ProjectContainer" "1" --> "*" "Project": contains
"Project" "1" --> "*" "Sprint": has
"Sprint" "1" --> "1" "SprintBacklog": has
"Sprint" "1" --> "1" "Period": has
"SprintBacklog" .--> "IFactoryUserStory"
"SprintBacklog" "1" --> "*" "UserStory": has
"IFactoryUserStory" .--> "UserStory"
"ViewScrumBoardController" .--> "ProjectDto": extracts
"ViewScrumBoardController" .--> "UserStoryDtoListAssembler": uses
"UserStoryDtoListAssembler" .--> "UserStoryMapper"
"UserStoryDtoListAssembler" .--> "SprintBacklog"
"UserStoryMapper" .--> "UserStoryDto": converts
"UserStoryMapper" .--> "UserStory"

@enduml