@startuml

skinparam sequenceMessageAlign center
title TO LIST ALL PROJECTS
legend top
US015 - As a Manager, I want to get a list of all projects
end legend

class "ListProjectController" {
-service
-projectMapper
+listAllProjects(email)
+listAllProjectsDTO()
}

class "Service" {
- company
+ validateManager(email)
+ listAllProjects ()
}

class "Company"{
-projectContainer
-accountContainer
+ validateManager(email)
+listAllProjects()
}

class "AccountContainer"{
-accounts
+validateManager(email)
+getAccountByEmail(email)
}

class "Account"{
+validateManager(email)
}

class "ProjectContainer"{
-projects
+getProject()
}

class "ProjectMapper"{
-projectDTO
+add(projectDTO)
+toDTO(project)
}

class "ProjectDTO" {
+createDTO(project)
}
"ListProjectController" ..> "Service"
"Service" ..> "Company"
"ListProjectController" ..> "ProjectMapper"
"Company" "1"-->"1" "ProjectContainer": has
"Company" "1"-->"1" "AccountContainer": has
"AccountContainer" --> "Account"
"ProjectMapper" --> "ProjectDTO"


@enduml