@startuml
legend top
US005 - As Administrator, I want to inactivate a user account.
US006 - As Administrator, I want to activate a user account.
end legend
skinparam sequenceMessageAlign center
title TO INACTIVATE/ACTIVATE USER ACCOUNT
autonumber
actor "Administrator" as administrator
participant ":ChangeStatusUI" as ui
participant ":ChangeStatusController" as controller

participant ":AccountChangeStatusService" as service
participant ":AccountRepository" as repository
participant "account:Account" as account

activate administrator

administrator -> ui : Changes account status to "Inactive"
activate ui
ui -->> administrator: requests data (email, status)
deactivate ui
administrator -> ui: Enters requested data
activate ui
ui -> controller: changeStatus(email, status)
activate controller
controller -> service: changeStatus(email, status)
activate service
service-> repository: getAccountByEmail(email)
activate repository
repository --> service: account
deactivate repository
service -> account: changeStatus(status)
activate account
service <-- account: true
deactivate account
deactivate repository
service --> controller: true
deactivate service
controller -->> ui: true
deactivate controller
ui -->> administrator: informs account status updated
deactivate ui

@enduml
