@startuml
skinparam sequenceMessageAlign center
title TO ADD A USER STORY TO THE SPRINT BACKLOG USING THE WEB UI
legend top
US020 - As Project Manager, I want to add a user story to the open/current sprint backlog using the web UI.
end legend
autonumber
actor "Project Manager"
participant ":AddUserStoryInSprintUI" as ui
participant ":SprintWebController" as ct
participant ":AddUserStoryToSprintBacklogService" as serv
participant ":SprintRepository" as rep
participant "sprint:Sprint" as sprint
participant ":SprintDataAssembler" as ass
participant ":ISprintJpaRepository" as i
activate "Project Manager"

"Project Manager"-> ui: starts adding a User Story to Sprint Backlog
activate ui
ui --> "Project Manager": requests data (usId, sprintId)
"Project Manager" -> ui: sends requested data
ui -> ct: addUserStoryToSprintBacklog(UserStoryInSprintDto)
activate ct
ct -> serv: addUserStoryToSprintBacklog(UserStoryInSprintDto)
activate serv
serv -> rep : getSprintById(sprintId)
activate rep
rep --> serv : sprint
deactivate rep
serv -> sprint : addUserStory(userStoryId)
activate sprint
sprint --> serv :true
deactivate sprint
serv -> rep : save(sprint)
activate rep
rep -> ass : toData
activate ass
ass -> i : save(sprint)
activate i
i --> ass : true
deactivate i
ass --> rep : sprintJpa
deactivate ass
rep --> serv : true
deactivate rep
serv --> ct : true
deactivate serv
ct --> ui : true
deactivate ct
ui --> "Project Manager": User Story was added to Sprint Backlog
deactivate ui
@enduml