@startuml

skinparam sequenceMessageAlign center
title TO DEFINE THE PRODUCT OWNER OF A PROJECT
legend top
US012 - As Manager, I want to define the Product Owner of a project
end legend

class DefineProductOwnerController {
-company
+addProductOwnerToProject(emailManager)
+addProductOwnerToProject(allocationDTO)
}

class Company {
-accountInProjectContainer
+addProductOwnerToProject(allocationDTO)
}

class AccountInProject{
-account
-project
-costPerHour
-percentageAllocation
-role
-startDate
-endDate
+AccountInProject(account, project, costPerHour, percentageAllocation, startDate, role)
}

class AccountInProjectContainer{
-accountsInProjects
+addProductOwnerToProject(accountInProject)
}

class AllocationMapper {
+addProductOwnerToProject(account, project...)
}

DefineProductOwnerController --> Company
Company "1"-->"1" AccountInProjectContainer: has
AccountInProjectContainer "1"..>"1" AllocationMapper
AllocationMapper "1"..> "*"AccountInProject: creates
AccountInProjectContainer "1"--> "*" AccountInProject: has

@enduml
