@startuml
skinparam sequenceMessageAlign center
title TO DEFINE THE PRODUCT OWNER OF A PROJECT
legend top
US012 - As Manager, I want to define the Product Owner of a project
end legend
autonumber


actor Manager
participant ":DefineProductOwnerUI" as ui
participant ":DefineProductOwnerController" as controller
participant ":Company" as company
participant "accountInProjectContainer:AccountInProjectContainer" as accinprojcont
participant ":AllocationMapper" as mapper
participant "accountInProject:AccountInProject" as accinproj

Manager -> ui: starts the definition of a product owner of a project
activate ui
ui -> controller: addProductOwnerToProject(emailManager)
activate controller
controller -> company: validateManager((emailManager)
activate company
ref over company: validateManager_sequenceDiagram
company --> controller: true
deactivate company
controller -> company: listAllUsers()
activate company
ref over company: listAllUSers_sequenceDiagram
company --> controller: users
deactivate company
controller -> company: listAllProjects()
activate company
ref over company: US015_sequenceDiagram
company --> controller: projects
deactivate company
controller --> ui: userAccountsDTO
controller --> ui: projectsDTO
deactivate controller
ui --> Manager: list of all Users/projects

deactivate ui

Manager -> ui: selects user/project
activate ui
Manager -> ui: sends data (costPerHour, percentageAllocation, startDate )
ui -> controller: addProductOwnerToProject(allocationDTO)
activate controller
controller -> company: addProductOwnerToProject(allocationDTO)
activate company
company -> accinprojcont: addProductOwnerToProject(allocationDTO)
activate accinprojcont
accinprojcont -> mapper: addProductOwnerToProject(allocationDTO)
activate mapper
create accinproj
mapper -> accinproj: create(account, project...)
mapper --> accinprojcont: acountInProject
deactivate mapper
accinprojcont -> accinprojcont: add(accountInProject)
accinprojcont --> company: true
deactivate accinprojcont
company --> controller: true
deactivate company
controller --> ui: true
deactivate controller
ui --> Manager: informs product owner defined
deactivate ui
@enduml