@startuml

skinparam sequenceMessageAlign center
title TO LIST ALL ACCOUNTS IN A GIVEN PROJECT
legend top
US014 - As Manager, I want to get a list of all human resources in a project.
end legend

class "ListAccountsInProjectController" {
-service
-accountMapper
+listAccountsByProject(email, projectCode)
}

class "Service"{
-company
+listAccountsByProject(email, projectCode)
}

class "Company"{
-projectContainer
-accountContainer
+validateManager(email)
+listAccountsByProject(projectCode)
}

class "AccountContainer"{
-accounts
+getAccountByEmail(email)
}

class "Account"{
-profile
+isManager()
}

class "ProjectContainer"{
-projects
-accountInProjectContainer
+listAccountsByProject(projectCode)
+getProjectByCode(projectCode)
}


class "AccountInProjectContainer"{
-accountsInProject
+listAccountsByProject(project)
}

class "AccountInProject"{
-account
-project
-role
+getAccountByProject(project)
}

class "AccountMapper"{
+accountsToDTO(accounts)
+accountToDTO(account)
}

class "AccountDTO"{
+name
+email
+phoneNumber
+AccountDTO(account)
}

"ListAccountsInProjectController" --> "Service"
"ListAccountsInProjectController" --> "AccountMapper"
"Service" ..> "Company"
"Company" "1"-->"1" "ProjectContainer": has
"Company" "1"-->"1" "AccountContainer": has
"AccountContainer" "1" --> "*" "Account"
"AccountMapper" ..> "AccountDTO"
"ProjectContainer" "1" --> "1" "AccountInProjectContainer": has
"AccountInProjectContainer" "1" --> "*" "AccountInProject": has
@enduml