@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam sequenceMessageAlign center
title CREATE A NEW PROJECT TYPOLOGY
legend top
US007 - As Administrator, I want to create a new project typology.
end legend

actor Administrator as a
participant ":UIProjectTypology" as ui
participant ":ProjectTypologyController" as ct
participant ":Service" as sv
participant ":Company" as c
participant ":AccountContainer" as acc
participant "account:Account" as ac
participant "ProjectTypologyContainer" as ptc
participant "pt:ProjectTypology" as pty


activate a
a -> ui: starts creating new project typology
activate ui
ui --> a: requests data (projectTypology)
a -> ui: types requested data
ui -> ct: createProjectTypology(email, projectTypology)
activate ct
ct -> sv: createProjectTypology(email, projectTypology)
activate sv
sv -> c: validateAdministrator(email)
activate c
c -> acc: validateAdministrator(email)
activate acc
acc -> acc: account = getAccountByEmail(email)
acc -> ac: validateAdministrator
activate ac
ac --> acc: true
deactivate ac
acc --> c: true
deactivate acc
c --> sv: true
deactivate c
sv -> c: createProjectTypology(projectTypology)
activate c
c -> ptc: createProjectTypology(projectTypology)
activate ptc
create pty
ptc -> pty: create()
ptc -> ptc: addProjectTypology(pt)
ptc --> c: true
deactivate ptc
c --> sv: true
deactivate c
sv --> ct: true
deactivate sv
ct --> ui: true
deactivate ct
ui --> a: project typology created
deactivate ui
deactivate a
@enduml

