@startuml

legend top
US007 -  As Administrator, I want to create a new project typology.
end legend
skinparam sequenceMessageAlign center
title CREATE A NEW PROJECT TYPOLOGY

"Controller" ..> "Company"
"Company" ..> "ProjectTypologyContainer"
"ProjectTypologyContainer" ..> "ProjectTypology"

class "Company" {
-projectContainer
createProjectTypology(projectTypology)
}
class "Controller" {
-company
createProjectTypology(projectTypology)
}
class "ProjectTypologyContainer"{
-typologies
addProjectTypology(projectTypology)
doesProjectTypologyExist(projectTypology)
}
class "ProjectTypology"{
-projectTypology
ProjectTypology(projectTypology)
}


@enduml