@startuml

class RegisterAccountController {
- accountService
+ registerAccount (accountCreationDto)
}

class AccountCreationService{
- accountRepository
- accountFactory
+ registerAccount(name, email, phoneNumber, photo)
}

interface IAccountFactory{
+ createAccount(name, email, phoneNumber, photo)
}

class AccountFactory{
+ createAccount(name, email, phoneNumber, photo)
}

interface IAccountRepository{
+ add(account)
}

class AccountRepository{
+ add(account)
}

class Account<<root>>{
- name
- email
-phoneNumber
-photo
}

RegisterAccountController <.. AccountCreationService: is injected
AccountCreationService <.. IAccountRepository: is injected
AccountCreationService <.. IAccountFactory: is injected
IAccountFactory <|.. AccountFactory: implements
AccountFactory ..> Account: creates
IAccountRepository <|.. AccountRepository: implements
AccountRepository --> Account: has


@enduml