@startuml

skinparam sequenceMessageAlign center
title TO REGISTER NEW ACCOUNT
legend top
US002 - As Administrator, I want to register a user.
end legend

class "RegisterAccountController" {
-company
+registerAccount(name, email, phoneNumber, photo)
}

class "Company" {
-accountContainer
+registerAccount(name, email, phoneNumber, photo)
}

class "AccountContainer"{
-accounts
+addAccount(account)
}

class "Account" {
-name
-email
-phoneNumber
-photo
}

"RegisterAccountController" "1" --> "1" "Company": has
"Company" "1"-->"1" "AccountContainer": has
"AccountContainer" "1"-->"*" "Account": contains

@enduml