@startuml
skinparam sequenceMessageAlign center
title TO REGISTER NEW ACCOUNT
legend top
US002 - As Administrator, I want to register a user.
end legend
autonumber
actor Administrator
participant ":RegisterAccountUI" as ui
participant ":RegisterAccountController" as controller
participant ":Company" as comp
participant "accountContainer:AccountContainer" as AC
participant "account:Account" as account
activate Administrator
Administrator -> ui: registers new account
activate ui
ui -->> Administrator: requests data (name, email, phoneNumber, photo)
deactivate ui
Administrator -> ui: types requested data
activate ui
ui -> controller: registerAccount (name, email, phoneNumber, photo)
activate controller
controller -> comp: registerAccount(name, email, phoneNumber, photo)
activate comp
comp -> AC: addAccount(name, email, phoneNumber, photo)
create account
activate AC
AC -->> account: create(name, email, phoneNumber, photo)
AC -> AC: add(account)
AC --> comp: true
deactivate AC
comp --> controller: true
deactivate comp
controller -->> ui: true
deactivate controller
ui-->> Administrator: informs account created
deactivate ui
@enduml
