@startuml
actor Administrator
participant ":RegisterAccountUI" as ui
participant ":registerAccountController" as controller
participant ":Company" as company
participant "reg:Account" as account

activate Administrator
Administrator -> ui: 1. starts new account register
activate ui
ui --> Administrator: 1.1 requests data(name, email, phoneNumber)
deactivate ui
Administrator -> ui: 2. types requested data
activate ui
ui -> controller: 2.1 registerAccount(name, email, phoneNumber)
activate controller
controller -> company: 2.1.1 reg=registerAccount(name, email, phoneNumber)
activate company
create account
company --> account: 2.1.1.1 registerAccount(name, email, phoneNumber)
activate account
company -> company: 2.1.1.2 validateAccount(reg)
deactivate account
ui --> Administrator: 2.2 shows data and requests confirmation
deactivate controller
deactivate company
deactivate ui
Administrator -> ui: 3. confirms
activate ui
ui -> controller: 3.1 saveAccount()
activate controller
controller -> company: 3.1.1 saveAccount()
activate company
company -> company: 3.1.1.1 saveAccount(reg)
company -> company: 3.1.1.2 validateAccount(reg)
company -> company: 3.1.1.3 addAccount(reg)

ui --> Administrator: 3.2 informs success!
deactivate company
deactivate controller
deactivate ui


@enduml

actor Administrator
participant ":RegisterAccountController" as controller
participant ":Company" as company
participant "acc :Account" as account

Administrator -> controller: 1. registerNewAccount(name, email, phoneNumber)
activate controller
controller -> company: 1.1 acc=registerNewAccount(name, email, phoneNumber)
activate company
create account
company --> account: 1.1.1 registerAccount(name, email, phoneNumber)
company -> company: 1.1.2 validateAccount(acc)
company -> company: 1.1.3 addAccount(acc)


actor Administrator
participant ":RegisterAccountUI" as ui
participant ":RegisterAccountController" as rgc
participant ":registerAccountController" as controller
participant "reg:Account" as account

activate Administrator
Administrator -> ui: 1. starts new account register
activate ui
ui --> Administrator: 1.1 requests data(name, email, phoneNumber)
deactivate ui
Administrator -> ui: 2. types requested data
activate ui
ui -> rgc: 2.1 registerAccount(name, email, phoneNumber)
activate rgc
rgc -> controller: 2.1.1 reg=registerAccount(name, email, phoneNumber)
activate controller
controller --> account: 2.1.1.1 register(name, email, phoneNumber)
deactivate controller
rgc -> controller: 2.1.2 validateAccount(reg)
activate controller
deactivate rgc
deactivate controller
ui --> Administrator: 2.2 shows data and requests confirmation

deactivate ui
Administrator -> ui: 3. confirms
activate ui
ui -> rgc: 3.1 saveAccount()
activate rgc
rgc -> controller: 3.1.1 saveAccount(reg)
activate controller
controller -> controller: 3.1.1.1 validateAccount(reg)
controller -> controller: 3.1.1.2 addAccount(reg)
deactivate controller
deactivate rgc
ui --> Administrator: 3.2 informs success!
deactivate ui
