@startuml
'https://plantuml.com/class-diagram

class "RegisterAccountUI"{
}

class "RegisterAccountController" {
+registerAccount(name, email, phoneNumber)
+saveAccount()
}

class "Company" {
+registerAccount(name, email, phoneNumber)
+validateAccount(account)
+saveAccount(account)
-addAccount(account)
}

class "Account" {
-name
-email
-phoneNumber
-photo
+Account(name,email,phoneNumber)
}

hide "Account" circle
hide "RegisterAccountController" circle
hide "RegisterAccountUI" circle
hide "Company" circle

"RegisterAccountUI" ..>  "RegisterAccountController"
"RegisterAccountController" ..>  "Company"
"Company" "1" --> "*" "Account": registers

@enduml