@startuml

class RegisterAccountUI
class RegisterAccountController
class System
class Account

class RegisterAccountController {
+registerAccount(name, email, phoneNumber)
+saveAccount()
}

class System {
+registerAccount(name, email phoneNumber)
+validateAccount(reg)
+saveAccount(reg)
-addAccount(reg)
}

class Account {
-name
-email
-phoneNumber
+Account(name, email, phoneNumber)
}

RegisterAccountUI ..> RegisterAccountController
RegisterAccountController ..> System
RegisterAccountController ..> Account
System "1" --> "*" Account: contains


hide RegisterAccountUI circle
hide RegisterAccountController circle
hide System circle
hide Account circle


@enduml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

hide ArrayList circle