@startuml

actor "Administrator" as admin
participant ":ChangeStatusUI" as ui
participant ":ChangeStatusController" as controller
participant ":Company" as company
participant "accountContainer:AccountContainer" as container
participant "account:Account" as account

activate admin
admin -> ui : Changes account status to "Inactive"
activate ui
ui --> admin: requests data (email, status)
deactivate ui
admin -> ui: Enters requested data
activate ui
ui -> controller: changeStatus(email, status)
activate controller
controller -> company: accountContainer = getAccountContainer()
activate company
deactivate company
controller -> container: account = getAccountByEmail(email)
activate container
deactivate container
controller -> account: setStatus(status)
activate account
deactivate account
controller --> ui: confirms
deactivate controller
ui --> admin: confirms
deactivate ui

@enduml

