@startuml

class "ChangeStatusUI" as CSUI
class "ChangeStatusController" as CSC
class "Company" as company
class "AccountContainer" as container
class "Account" as account

"CSUI" ..> "CSC"
"CSC"  ..> "company"
"CSC" ..> "container"
"CSC" ..> "account"
"company" "1"-->"1" "container": has
"container" "1"-->"*" "account": contains

hide "CSUI" circle
hide "CSC" circle
hide "company" circle
hide "container" circle
hide "account" circle

class "CSC" {
-company
+changeStatus(email, status)
}

class "company" {
-accountContainer
+getAccountContainer()
}

class "container" {
-accountList
+getAccountByEmail(email)
}

class "account" {
-email
-status
+setStatus(status)
}

@enduml