@startuml
'https://plantuml.com/class-diagram

class Account
class ChangeStatusController
hide ChangeStatusController circle
hide Account circle

ChangeStatusController "1" -->"*"Account

class ChangeStatusController{
+changesStatus(inactive)
+isStatusValid(inactive)
}
class Account{

+ updateStatus(inactive)
}

@enduml