@startuml
'https://plantuml.com/sequence-diagram
skinparam sequenceMessageAlign center
title TO CREATE NEW SPRINT
legend top
US019 - As Project Manager, I want to create a sprint.
end legend
autonumber

actor ProjectManager
participant ":System" as sys

ProjectManager -> sys : starts creating new sprint
note left: Account is authenticated. \n":System" grants access.
sys --> ProjectManager : requests data(sprintNumber, startDate, projectCode)
ProjectManager -> sys : types requested data
sys --> ProjectManager: informs operation success

@enduml