@startuml
'https://plantuml.com/class-diagram
skinparam sequenceMessageAlign center
title TO CREATE NEW SPRINT
legend top
US019 - As Project Manager, I want to create a Sprint.
end legend

class CreateSprintController {
- company
+ createSprint(projectDto,sprintDto)
}
CreateSprintController "1"-->"1" Company: has

class Company {
-projectContainer
+createSprint(projectDto,sprintDto)
}
Company "1"-->"1" ProjectContainer : has

class ProjectContainer {
-project
+createSprint(sprintDto)
-getProjectByCode(projectDto)
}
ProjectContainer "1"-->"*" Project: has

class Project {
-factorySprint
-sprints
+createSprint(sprintNumber,startDate, projectCode)
+isSprintUnique(sprint)
+isPeriodValid(sprint, existingSprint)
+hasProjectCode(projectCode)
}
Project "1"-->"1" FactorySprint: has

interface FactorySprint {
+createSprint(startDate, sprintDuration)
}

class Sprint {
-sprintNumber
-FactoryPeriod
-Period
-SprintBacklog
+Sprint(startDate, sprintDuration, sprintNumber)
+createPeriod(startDate,sprintDuration)
+getStartDate()
+getEndDate()
}

Sprint -> FactoryPeriod
FactorySprint "1"..> "*"Sprint

interface FactoryPeriod {
+create(startDate, sprintDuration)
}

FactoryPeriod ..> Period

class Period {
-startDate
-endDate
-calculateEndDate( startDate, sprintDuration)
+Period(startDate, sprintDuration)
+getStartDate()
+getEndDate()
}
@enduml