@startuml
skinparam sequenceMessageAlign center
title TO CLOSE A CURRENT/ACTIVE SPRINT OF A PROJECT
legend top
US034 - As Project Manager, I want to close the current/active sprint of a project in the web UI.
end legend
autonumber

actor "Project Manager"
participant ":CloseSprintUi" as ui
participant ":SprintWebController" as controller
participant ":SprintStatusChangeService" as service
participant ":SprintRepository" as sprintRepo
participant "sprint:Sprint" as sprint
participant ":UserStoryRepository" as usRepo
participant "userStory:UserStory" as us


activate "Project Manager"
"Project Manager" -> ui: asks to close a current sprint of a project
activate ui
ui --> "Project Manager": requests confirmation
deactivate ui
"Project Manager" -> ui: confirms
activate ui
ui -> controller: patch ("/sprints") {sprintId}
activate controller
controller -> service: changeSprintStatus(SprintStatusDto)
activate service
service -> sprintRepo: sprint = findById(sprintId)
activate sprintRepo
sprintRepo --> service: sprint
deactivate sprintRepo
opt sprintStatusDto.status == open

service -> sprint: isOpen(sprint)
activate sprint
sprint -> service: true
deactivate sprint
service -> usRepo: userStories = getListOfUsWithMatchingIds(sprint.getSprintBacklog)
activate usRepo
usRepo --> service: userStories
deactivate usRepo
loop for each userStory in userStories
service -> us: hasStatus(blocked) || hasStatus(running)
activate us
us --> service: true
deactivate us

service -> us: changeStatus(status)
activate us
us --> service: true
deactivate us
service -> usRepo: save(userStory)
activate usRepo
usRepo --> service: true
deactivate usRepo

end loop
service -> sprint: changeStatus(status)
activate sprint
sprint --> service: true
end opt
deactivate sprint
service --> controller: ok
deactivate service
controller --> ui: ok
deactivate controller
ui --> "Project Manager": informs about operation success
deactivate ui

@enduml