@startuml
skinparam sequenceMessageAlign center
title TO CREATE NEW PROFILE
legend top
US001 - As Administrator, I want to create user profiles.
end legend
autonumber


actor Administrator as a
participant ":CreateProfileUI" as ui
participant "CreateProfileController" as ct
participant ":ProfileService" as s
participant ":ProfileFactory" as fp
participant "profile:Profile" as profile
participant "ProfileRepository" as pr



activate a
a -> ui: starts creating new profile
activate ui
ui --> a: requests data (profileName)
a -> ui: types requested data
ui -> ct: createProfile(profileName)
activate ct

deactivate s
ct -> s: createProfile(profileName)
activate s
s -> fp: createProfile(profileName, idProfileNumber)
activate fp
create profile
fp -> profile

fp --> s: profile
deactivate fp
s -> pr: addProfile(name, id)


s --> ct: true
deactivate s
ct --> ui: true
deactivate ct
ui --> a: informs operation success
deactivate ui

deactivate a
@enduml
