@startuml

skinparam sequenceMessageAlign center
title TO CREATE NEW PROFILE
legend top
US001 - As Administrator, I want to create user profiles.
end legend
autonumber


actor Administrator as a
participant ":CreateProfileUI" as ui
participant "CreateProfileController" as ct
participant ":Company" as c
participant "ProfileContainer" as cn
participant "profile:Profile" as p


activate a
a -> ui: starts creating new profile
activate ui
ui --> a: requests data (profileName)
a -> ui: types requested data
ui -> ct: createProfile(profileName)
activate ct
ct -> c: validateProfileRequired(email, profileNameRequired)
activate c
ref over c: validateAdministrator_sequenceDiagram
c --> ct: true
deactivate c
ct -> c: createProfile(profileName)
activate c
c -> cn: createProfile(name)
activate cn
create p
cn -> p: create()
cn -> cn: addProfile(name)
cn --> c: true
deactivate cn
c --> ct: true
deactivate c
ct --> ui: true
deactivate ct
ui --> a: informs operation success
deactivate ui

deactivate a
@enduml


