@startuml
'https://plantuml.com/class-diagram
skinparam sequenceMessageAlign center
title TO DEFINE THE PO OF A PROJECT
legend top
US012 - As Manager, I want to define the PO of a project
end legend
autonumber

actor Manager
participant ":SetRoleUI" as ui
participant "SetRoleController" as controller
participant ":Company" as company
participant ":AccountContainer" as acccontainer
participant ":ProjectContainer" as pcontainer
participant ":AccountInProjectContainer" as accinprojcont
participant ":AccountInProject" as accinproj


Manager -> ui:  defines a PO of a project
activate ui
Manager <-- ui:  requests data (email,projectCode, role)
deactivate ui
Manager -> ui:  enters data
activate ui
ui -> controller: setRole(email, projectCode, role)
activate controller
controller -> company: setRole (email, projectCode, role)
activate company
company -> acccontainer: getAccountByEmail(email)
activate acccontainer
company <-- acccontainer: account
deactivate acccontainer
company -> pcontainer: getProject(projectCode)
activate pcontainer
company <-- pcontainer: project
deactivate pcontainer
company -> accinprojcont: setRole(account, project,role)
activate accinprojcont
accinprojcont -> accinprojcont : getAccountInProject(account,project)
accinprojcont -> accinproj: SetRole(role)
activate accinproj
accinproj --> accinprojcont: true

deactivate accinproj
accinprojcont --> company: true
deactivate accinprojcont
company --> controller : true
deactivate company
controller --> ui: true
deactivate controller
ui -->> Manager: informs Set Role


@enduml


