@startuml

legend top
US007 -  As Administrator, I want to create a new project typology.
end legend
skinparam sequenceMessageAlign center
title CREATE A NEW PROJECT TYPOLOGY

"CreateProjectTypologyController""1"-->"1" "Company": has
"Company" "1"-->"1" "ProjectTypologyContainer" : has
"Company" "1"-->"1" "AccountContainer" : has
"ProjectTypologyContainer" "1"-->"*" "ProjectTypology" : has
"AccountContainer" "1"-->"*" "Account" : has
"Account" "*"-->"1" "Profile" : has

class "CreateProjectTypologyController" {
- company
+createProjectTypology(email, projectTypology)
}
class "Company" {
-accountContainer
-projectTypologyContainer
+createProjectTypology(projectTypology)
+validateAdministrator(email)
}
class "ProjectTypologyContainer"{
-typologies
+createProjectTypology(projectTypology)
-doesProjectTypologyExist(projectTypology)
}
class "AccountContainer"{
-accounts
+validateAdministrator(email)
+getAccountByEmail(email)
}

class Profile{
-profileName
+isAdministrator()
}

class "ProjectTypology"{
-name
+ProjectTypology(name)
}

class "Account"{
-name
-email
-phoneNumber
-profile
-status
-photo
+isAdministrator()
}

@enduml