@startuml

legend top
US007 -  As Administrator, I want to create a new project typology.
end legend
skinparam sequenceMessageAlign center
title CREATE A NEW PROJECT TYPOLOGY


class "CreateProjectTypologyController" {
- company
+createProjectTypology(email, projectTypology)
}

class "Company" {
-projectTypologyContainer
-accountContainer
+validateProfileRequired(email, profileNameRequired)
+createProjectTypology(projectTypology)
}

class "ProjectTypologyContainer"{
-typologies
+createProjectTypology(projectTypology)
-doesProjectTypologyExist(projectTypology)
}

class "AccountContainer"{
-accounts
+validateProfileRequired(email, profileNameRequired)
+getAccountByEmail(email)
}

class Profile{
-profileName
+isProfileRequired(profileNameRequired)
}

class "ProjectTypology"{
-name
+ProjectTypology(name)
}

class "Account"{
-email
+isProfileRequired(profileNameRequired)
}


"CreateProjectTypologyController""1"-->"1" "Company": has
"Company" "1"-->"1" "ProjectTypologyContainer" : has
"Company" "1"-->"1" "AccountContainer" : has
"ProjectTypologyContainer" "1"-->"*" "ProjectTypology" : has
"AccountContainer" "1"-->"*" "Account" : has
"Account" "*"-->"1" "Profile" : has

@enduml