@startuml
'https://plantuml.com/sequence-diagram


actor "Administrator"
participant ":ChangeAccountController" as rgc
participant ":Account" as Account


Administrator -> rgc: 1. Changes status to active
activate rgc
rgc -> rgc: 2. isStatusValid(active)
rgc -> Account: 3. changesStatus(active)
activate Account
deactivate Account
deactivate rgc

@enduml