@startuml
'https://plantuml.com/class-diagram

class "ChangeAccountUI"
class "ChangeStatusController"
class "Company"
class "Account"
annotation "Dependency"
annotation "Association"

"ChangeAccountUI" ..> "ChangeStatusController"
"ChangeStatusController"  ..> "Company"
"ChangeStatusController" ..> "Account"
"Company" "1  " -->"*" "Account"

("ChangeAccountUI", "ChangeStatusController") . "Dependency"
("Company", "ChangeStatusController") . "Dependency"
("Company", "Account") . "Association"


class "Company"{
+changeAccount(status)
+validateStatus(status)
+saveStatus(status)
-validateStatus
}
class "ChangeStatusController"{
+changeStatus(status)
-status
}

class Account{
+ change(status)
-status
}

@enduml