@startuml
'https://plantuml.com/class-diagram

class Account
class ChangeStatusController
hide ChangeStatusController circle
hide Account circle



ChangeStatusController "1" -->"*"Account


class ChangeStatusController{
+changesStatus(active)
+isStatusValid(active)
}
class Account{

+ updateStatus(active)
}


@enduml