@startuml

legend top
US006 - As Administrator, I want to activate a user account.
end legend
skinparam sequenceMessageAlign center
title TO ACTIVATE USER ACCOUNT
autonumber
actor "Administrator" as admin
participant ":ChangeStatusUI" as ui
participant ":ChangeStatusController" as controller
participant ":Company" as company
participant "accountContainer:AccountContainer" as container
participant "account:Account" as account

activate admin
admin -> ui : Changes account status to "Active"
activate ui
ui --> admin: requests data (email, status)
deactivate ui
admin -> ui: Enters requested data
activate ui
ui -> controller: changeStatus(email, status)
activate controller
controller -> company: accountContainer = getAccountContainer()
activate company
create container
company -->> container: create
deactivate company
controller -> container: account = getAccountByEmail(email)
activate container
create account
container -->> account: create
deactivate container
controller -> account: setStatus(status)
activate account
deactivate account
controller --> ui: account status updated
deactivate controller
ui --> admin: informs account status updated
deactivate ui

@enduml
