@startuml
'https://plantuml.com/sequence-diagram


actor "Administrator"
participant ":Controller" as rgc
participant ":Account" as Account


Administrator -> rgc: 1 changesStatus(status)
activate rgc
rgc -> rgc: 1.1 isStatusValid(status)
rgc -> Account: 1.2  updateStatus(status)
activate Account
deactivate Account
deactivate rgc

@enduml