@startuml

legend top
US006 - As Administrator, I want to activate a user account.
end legend
skinparam sequenceMessageAlign center
title TO ACTIVATE USER ACCOUNT

"ChangeStatusController" ..> "Company"
"ChangeStatusController" ..> "AccountContainer"
"ChangeStatusController" ..> "Account"
"Company" "1"-->"1" "AccountContainer": has
"AccountContainer" "1"-->"*" "Account": contains

class "ChangeStatusController" {
-company
+changeStatus(email, status)
}

class "Company" {
-accountContainer
+getAccountContainer()
}

class "AccountContainer" {
-accounts
+getAccountByEmail(email)
}

class "Account" {
-email
-status
+setStatus(status)
}

@enduml