@startuml
'https://plantuml.com/class-diagram

class "ChangeAccountUI"
class "ChangeAccountController"
class "Company"
class "Account"
annotation "Dependency"
annotation "Association"

"ChangeAccountUI" ..> ChangeAccountController
"ChangeAccountController"  ..> "Company"
"ChangeAccountController" ..> "Account"
"Company" "1" -->"*" "Account"

("ChangeAccountUI", "ChangeAccountController") . "Dependency"
("Company", "ChangeAccountController") . "Dependency"
("Company", "Account") . "Association"


class "Company"{
+changeAccount(status)
+validateStatus(status)
+saveStatus(status)
-validateStatus
}
class "ChangeAccountController"{
+changeStatus(status)
+saveStatus()
}

class Account{
+ change(status)
-status
}

@enduml