@startuml

legend top
US005 - As Administrator, I want to activate a user account.
end legend
skinparam sequenceMessageAlign center
title TO ACTIVATE USER ACCOUNT

class "ChangeStatusController" {
-company
+changeStatus(email, status, actorEmail)
}

class "Company" {
-accountContainer
+validateProfileRequired(email, profileNameRequired)
+changeStatus(email, status)
}

class "AccountContainer" {
-accounts
+validateProfileRequired(email, profileNameRequired)
+getAccountByEmail(email)
}

class "Account" {
-status
+ isProfileRequired(profileNameRequired)
+ setStatus(status)
}
class "Profile"{
-profileName
+isProfileRequired(profileNameRequired)
}


"ChangeStatusController" --> "Company"
"Company" "1"-->"1" "AccountContainer": has
"AccountContainer" "1"-->"*" "Account": contains
"Account" "*"--> "1""Profile": contains


@enduml