@startuml
skinparam sequenceMessageAlign center
title TO LIST ALL ACCOUNTS IN A GIVEN PROJECT
legend top
US014 - As Manager, I want to get a list of all human resources in a project.
end legend
class "ListAccountsInProjectController" {
-company
+listAccountsByProject(emailActor, projectCode)
}

class "Company"{
-accountsInProjectContainer
-accountContainer
+validateProfileRequired(email, profileNameRequired)
+listAccountsByProject(projectCode)
}

class "AccountInProjectContainer"{
-accountsInProject
+listAccountsByProject(projectCode)
}

class "AccountInProject"{
-account
-project
+getAccountByProject(projectCode)
-hasProject(projectCode)
}

class "AccountContainer" {
-accounts
+validateProfileRequired(email, profileNameRequired)
+getAccountByEmail(email)
}

class "Account" {
-email
-profile
-status
+equals(Object toCompare)
+hashCode()
+checkAccountFromEmail(email)
+isProfileRequired(profileNameRequired)
+getAccountName()
+getEmail()
+getAccountStatus()
}

class "Profile"{
-profileName
+isProfileRequired(profileNameRequired)
+equals(Object toCompare)
+hashCode()
}

class "AccountMapper"{
+listAccountsToDto(accounts)
+accountToDto(account)
}

class "AccountDto"{
+name
+email
+status
+equals(Object toCompare)
+hashCode()
}

class "Project"{
-projectCode
+equals(Object toCompare)
+hashCode()
+hasProjectCode(projectCode)
}

"ListAccountsInProjectController" --> "Company"
"ListAccountsInProjectController" ..> "AccountMapper"
"Company" "1"-->"1" "AccountInProjectContainer": has
"Company" "1" --> "1" "AccountContainer": has
"AccountContainer" "1" --> "*" "Account": contains
"Account" "1" --> "1""Profile": has
"AccountMapper" ..> "AccountDto"
"AccountInProjectContainer" "1" --> "*" "AccountInProject": contains
"AccountMapper"..>"Account"
"AccountInProject" "1"-->"1" "Project": has
@enduml