@startuml
skinparam sequenceMessageAlign center
title TO LIST ALL ACCOUNTS IN A GIVEN PROJECT
legend top
US014 - As Manager, I want to get a list of all human resources in a project.
end legend
autonumber
actor Manager
participant ":ListAccountsInProjectUI" as ui
participant ":ListAccountsInProjectController" as ct
participant ":Company" as c
participant ":AccountInProjectContainer" as cn
participant ":AccountInProject" as acip
participant ":Project" as p
participant "accounts: List<Account>" as list
participant ":AccountMapper" as mapper
participant "accountsDTO: List<AccountDTO>" as listacDTO
participant "accountDTO:AccountDTO" as DTO


activate Manager
Manager -> ui: lists all accounts of a given project
activate ui
ui --> Manager: request data (projectCode)
Manager -> ui: types requested data
ui -> ct: listAccountsByProject(emailActor, projectCode)
activate ct
ct -> c: validateProfileRequired(email, profileNameRequired)
activate c
ref over c: validateManager_sequenceDiagram
c -->> ct: true
deactivate c
ct -> c: listAccountsByProject(projectCode)
activate c
c -> cn: listAccountsByProject(projectCode)
activate cn
create list
cn --> list :create()
loop for each AccountInProject in AccountInProjectContainer
cn -> acip : getAccountByProject(projectCode)
activate acip
acip -> p : hasProjectCode(projectCode)
activate p
p --> acip : true
deactivate p
acip --> cn: account
deactivate acip
cn -> list : add(account)
activate list
deactivate list
end loop
cn --> c : accounts
deactivate cn
c --> ct: accounts
deactivate c
ct -> mapper: listAccountsToDTO(accounts)
activate mapper
create listacDTO
mapper --> listacDTO: create ()
loop for each account in accounts
mapper -> list: get(i)
activate list
list --> mapper: account
deactivate list
activate mapper
mapper -> mapper : accountDTO = accountToDTO(account)
create DTO
mapper --> DTO : create()
mapper ->listacDTO :add(accountDTO)
deactivate mapper
activate listacDTO
end loop
deactivate listacDTO
mapper --> ct :accountsDTO
deactivate mapper
ct -->> ui: accountsDTO
deactivate ct
ui --> Manager: show list of accounts
deactivate ui
@enduml