@startuml
skinparam sequenceMessageAlign center
title TO LIST ALL ACCOUNTS IN A GIVEN PROJECT
legend top
US014 - As Manager, I want to get a list of all human resources in a project.
end legend
class "ListAccountsInProjectController" {
-company
+listAccountsByProject(emailActor, projectCode)
}

class "Company"{
-accountsInProjectContainer
-accountContainer
+validateManager(emailActor)
+listAccountsByProject(projectCode)
}

class "AccountInProjectContainer"{
-accountsInProject
+listAccountsByProject(projectCode)
}

class "AccountInProject"{
-account
-project
+getAccountByProject(projectCode)
-hasProject(projectCode)
}

class "AccountContainer" {
-accounts
+validateManager(email)
}

class "Account" {
-email
-profile
-status
+checkAccountFromEmail(email)
+isManager()
+getAccountName()
+getEmail()
+getAccountStatus()
}

class "Profile"{
-profileName
+isManager()
}

class "AccountMapper"{
+listAccountsToDTO(accounts)
+accountToDTO(account)
}

class "AccountDTO"{
+name
+email
+status
}

class "Project"{
-projectCode
+hasProjectCode(projectCode)
}

"ListAccountsInProjectController" --> "Company"
"ListAccountsInProjectController" ..> "AccountMapper"
"Company" "1"-->"1" "AccountInProjectContainer": has
"Company" "1" --> "1" "AccountContainer": has
"AccountContainer" "1" --> "*" "Account": contains
"Account" "1" --> "1""Profile": has
"AccountMapper" ..> "AccountDTO"
"AccountInProjectContainer" "1" --> "*" "AccountInProject": contains
"AccountMapper"..>"Account"
"AccountInProject" "1"-->"1" "Project": has
@enduml