@startuml
skinparam sequenceMessageAlign center
title TO LIST ALL ACCOUNTS IN A GIVEN PROJECT
legend top
US014 - As Manager, I want to get a list of all human resources in a project.
end legend


class "ListAccountsInProjectController" {
-service
+listAccountsInProject(code)
}

class "ResourceListAllocationService" {
-iResourceRepository
-iAccountRepository
-accountMapper
+listAccountsInProject(code)
}

interface "IProjectResourceRepository" {
+findAccountEmailsByProjectCode(code)
}

class "ProjectResourceRepository" {
-resources
+findAccountEmailsByProjectCode(code)
}

interface "IAccountRepository" {
+findAccountsByEmails(email)
+findAccountByEmail(email)
}

class "AccountRepository" {
- accounts
+findAccountsByEmails(email)
+findAccountByEmail(email)
}

class "AccountMapper" {
+ accountToDto(account)
+ accountsToDto(accounts)
}

class "AccountDto" {
+ name
+ email
+ status
#AccountDto(name, email, status)
}

class "Account" {
- name
- email
- status
+hasEmail(email)
+getAccountName()
+getAccountEmail()
+getAccountStatus()
}

class "ProjectResource" {
-code
-email
+hasProjectCode(code)
+getEmail()
}

ListAccountsInProjectController <.. ResourceListAllocationService: is injected

ResourceListAllocationService <.. IAccountRepository: is injected
IAccountRepository <|.. AccountRepository: implements
AccountRepository --> Account: has

ResourceListAllocationService <.. IProjectResourceRepository: is injected
IProjectResourceRepository <|.. ProjectResourceRepository: implements
ProjectResourceRepository --> ProjectResource: has

ResourceListAllocationService <.. AccountMapper: is injected
AccountMapper ...> AccountDto: creates
AccountDto ..> Account: uses

@enduml