@startuml
skinparam sequenceMessageAlign center
title TO LIST ALL ACCOUNTS IN A GIVEN PROJECT
legend top
US014 - As Manager, I want to get a list of all human resources in a project.
end legend
autonumber
actor Manager
participant ":ListAccountsInProjectUI" as ui
participant ":ListAccountsInProjectController" as controller
participant ":Company" as company
participant ":AccountInProjectContainer" as aipc
participant ":AccountInProject" as aip
participant "accounts: List<Account>" as list
participant ":AccountMapper" as mapper
participant "accountsDTO: List<AccountDTO>" as listDTO
participant "accountDTO:AccountDTO" as DTO
activate Manager
Manager -> ui: lists all accounts of a given project
activate ui
ui --> Manager: request data (projectCode)
Manager -> ui: types requested data
ui -> controller: listAccountsByProject(emailManager, projectCode)
activate controller
controller -> company: validateManager(emailManager)
activate company
ref over company: validateManager_sequenceDiagram
company -->> controller: true
deactivate company
controller -> company: listAccountsByProject(projectCode)
activate company
company -> aipc: listAccountsByProject(projectCode)
activate aipc
create list
aipc --> list :create()
loop for each AccountInProject in AccountInProjectContainer
aipc -> aip : getAccountByProject(projectCode)
activate aip
aip --> aipc : account
deactivate aip
aipc -> list : add(account)
activate list
deactivate list
end loop
aipc --> company : accounts
deactivate aipc
company --> controller: accounts
deactivate company
controller -> mapper: listAccountsToDTO(accounts)
activate mapper
create listDTO
mapper --> listDTO: create ()
loop for each account in accounts
mapper -> list: get(i)
list --> mapper: account
activate mapper
mapper -> mapper : accountDTO = accountToDTO(account)
create DTO
mapper --> DTO : create()
mapper ->listDTO :add(accountDTO)
deactivate mapper
activate listDTO
end loop
deactivate listDTO
mapper --> controller :accountsDTO
deactivate mapper
controller -->> ui: accountsDTO
deactivate controller
ui --> Manager: return list of accounts
deactivate ui
@enduml