@startuml
skinparam sequenceMessageAlign center
title TO ADD A CUSTOMER
legend top
US009 - As Administrator, I want to add a customer
end legend
autonumber
actor Administrator
participant ":AddCustomerUI" as ui
participant ":AddCustomerController" as controller
participant ":Company" as company
participant ":AccountContainer" as accContainer
participant "account :Account" as acc
participant ":CustomerContainer" as container
participant "customer:Customer" as customer

activate Administrator
Administrator -> ui: starting adding new customer
activate ui
ui --> Administrator: requests data (customerName)
deactivate ui
Administrator -> ui: sends requested data
activate ui
ui -> controller: addCustomer(email, customerName)
activate controller
controller -> company: addCustomer(email, customerName)
activate company
company -> accContainer: validateAdministrator(email)
activate accContainer
accContainer -> accContainer: getAccountByEmail(email)
accContainer -> acc: validadeAdministrator(email)
activate acc
acc --> accContainer: true
deactivate acc
accContainer --> company: true
deactivate accContainer
company --> controller: true
deactivate company
controller -> company: addCustomer(customerName)
activate company
company -> container: addCustomer(customerName)
create customer
activate container
container ->> customer: create(customerName)
container -> container: addCustomer(customer)
container --> company: true
deactivate container
company --> controller: true
deactivate company


controller -->> ui: true
deactivate controller
ui -->>Administrator: informs operation success
deactivate ui

@enduml