@startuml
skinparam sequenceMessageAlign center
title TO ADD A CUSTOMER
legend top
US009 - As Administrator, I want to add a customer
end legend
autonumber
actor Administrator
participant ":AddCustomerUI" as ui
participant ":AddCustomerController" as ct
participant ":Company" as c
participant ":CustomerContainer" as cn
participant "customer:Customer" as customer
activate Administrator
Administrator -> ui: starting adding new customer
activate ui
ui --> Administrator: requests data (customerName, customerNIF)

Administrator -> ui: sends requested data

ui -> ct: addCustomer(customerName, customerNIF, email)
activate ct
ct -> ct: validateProfileRequired(email, profileNameRequired)
activate c
ref over c: validateAdministrator_sequenceDiagram

c --> ct: true
deactivate c
ct -> c: addCustomer(customerName, customerNIF)
activate c

c -> cn: addCustomer(customerName, customerNIF)
create customer
activate cn

cn ->> customer: create(customerName, customerNIF)
cn -> cn: addCustomer(customer)
cn --> c: true
deactivate cn
c --> ct: true
deactivate c
ct -->> ui: true
deactivate ct
ui -->>Administrator: informs operation success
deactivate ui
@enduml