@startuml

skinparam sequenceMessageAlign center
title TO CHANGE PROFILE
legend top
US003 - As Administrator, I want to change the profile of a user account.
end legend

class ChangeProfileController {
-company
+changeProfile(email, profileName)
}

class Company {
-profileContainer
-accountContainer
+changeProfile(email, (profileName))
}

class ProfileContainer {
-profiles
+getProfileByName(profileName)
}

class AccountContainer {
-accounts
+getAccountByEmail(email)
}

class Account{
-email
-profile
+checkAccountFromEmail(email)
+setProfile(profile)
}

class Profile{
-profileName
+ checkProfileByProfileName(profileName)
}


ChangeProfileController --> Company
Company "1"-->"1" AccountContainer: has
Company "1"-->"1" ProfileContainer: has
Company ..> Account
AccountContainer "1"-->"*" Account: contains
ProfileContainer "1"-->"*" Profile: contains
Account "*"-->"1" Profile: has

@enduml
