@startuml
legend top
US003 - As Administrator, I want to change the profile of a user account.
end legend
skinparam sequenceMessageAlign center
title TO CHANGE PROFILE

class ChangeProfileController {
-changeProfileService
+changeProfile(email, profileName)
}

class ChangeProfileService {
-accountRepository
-profileRepository
+changeProfile(email, profileName)
}

class AccountRepository{
+getAccountByEmail(email)
}

class ProfileRepository{
+getProfileByName(profileName)
}

interface IAccountRepository{
+getAccountByEmail(email)
}

interface IProfileRepository{
+getProfileByName(profileName)
}

class Account <<root>>{
-email
-profile
+hasEmail(email)
+setProfile(profile)
}

class Profile <<root>>{
-profileName
+hasName(profileName)
}

AccountRepository "1"->"*" Account: has
ProfileRepository "1"->"*" Profile: has
ChangeProfileController"1 " <.. "1 "ChangeProfileService: is injected
IAccountRepository ..> ChangeProfileService : is injected
IProfileRepository ..> ChangeProfileService : is injected
AccountRepository ..> IAccountRepository : implements
ProfileRepository ..> IProfileRepository : implements
@enduml