@startuml

skinparam sequenceMessageAlign center
title TO CHANGE PROFILE
legend top
US003 - As Administrator, I want to change the profile of a user account.
end legend

class ChangeProfileController {
-company
+changeProfile(email, profileName, actorEmail)
}

class Company {
-profileContainer
-accountContainer
+validateProfileRequired(email, profileNameRequired)
+changeProfile(email, profileName)
}

class ProfileContainer {
-profiles
+getProfileByName(profileName)
}

class AccountContainer {
-accounts
+validateProfileRequired(email, profileNameRequired)
+getAccountByEmail(email)
}

class Account{
-email
-profile
+equals(Object toCompare)
+hashCode()
+ isProfileRequired(profileNameRequired)
+checkAccountFromEmail(email)
+setProfile(profile)
}

class Profile{
-profileName
+ isProfileRequired(profileNameRequired)
+equals(Object toCompare)
+hashCode()
}


ChangeProfileController "1"-->"1" Company
Company "1"-->"1" AccountContainer: has
Company "1"-->"1" ProfileContainer: has
AccountContainer "1"-->"*" Account: contains
ProfileContainer "1"-->"*" Profile: contains
Account "*"-->"1" Profile: has

@enduml
