@startuml


actor Administrator
participant ":ChangeProfileUI" as ui
participant ":ChangeProfileController" as controller
participant ":Company" as company
participant ":ProfileContainer" as profileContainer
participant ":AccountContainer" as accountContainer
participant "profile:Profile" as pf
participant "account:Account" as account



skinparam sequenceMessageAlign center
title TO CHANGE PROFILE
legend top
US003 - As Administrator, I want to change the profile of a user account.
end legend
autonumber

activate Administrator
Administrator -> ui:  Changes account profile
activate ui
Administrator <-- ui:  Requests data (email, profileName)
Administrator -> ui:  Enters account data
ui -> controller: changeProfile(email, profileName, actorEmail)
activate controller
controller -> company: validateProfileRequired(email, profileNameRequired)
activate company
ref over company: validateAdministrator_sequenceDiagram
company -->> controller: true
deactivate company
controller -> company: changeProfile(email, profileName)
activate company
company -> profileContainer: getProfileByName(profileName)
activate profileContainer
profileContainer -> pf: isProfileRequired(profileNameRequired)
activate pf
pf --> profileContainer : true
deactivate pf
company <-- profileContainer: profile
deactivate profileContainer
company -> accountContainer: getAccountByEmail(email)
activate accountContainer
accountContainer -> account: checkAccountFromEmail(email)
activate account
account --> accountContainer: true
deactivate account
company <-- accountContainer: account
deactivate accountContainer
company -> account: setProfile(profile)
activate account
deactivate account
controller <-- company: true
deactivate company
controller --> ui: true
deactivate controller
ui -->> Administrator: informs account profile updated
deactivate ui


@enduml