@startuml
title Packages Diagram
package "Project G4" {
    package Components {
        file Button.js
        file ConfirmationPage.js
        file DateInput.js
        file DatePickerInput.js
        file Footer.js
        file FailureMessage.js
        file SuccessMessage.js
        file InputText.js
        file Loading.js
        file Nav.js
        file NavItem.js
        file TableBody.js
        file TableHeader.js
        file AlertMessage.js
        file Form.js
        file Calendar.js
        file Header.js
        file Table.js
    }

    package Context {
        file Actions.js
        file AppContext.js
        file AppProvider.js
        file Reducer.js
    }

    package Pages {
        file About.js
        file AllocateResource.js
        file ConsultProductBacklog.js
        file CreateProject.js
        file CreateSprint.js
        file CreateUserStory.js
        file Home.js
        file ListProjects.js
        file Project.js
    }

    package Router {
        file Router.js
    }

    package Services {
        file api.js
        file ProjectService.js
        file ResourceService.js
        file SprintService.js
        file USerStoryService.js
    }

    Context  <... Pages: use
    Pages ...> Components: import
    Router ...> Pages: renders
    Context .....> Services: use



}
@enduml
