@startuml

class "CreateProfileController" {
-company
+createProfile(profileName)
}

class "RegisterAccountController" {
-company
+registerAccount(name, email, phoneNumber, photo, status)
}

class ChangeProfileController {
-company
+changeProfile(email, profileName)
}

class "ListAccountController" {
-company
+listAllAccounts()
}

class "ChangeStatusController" {
-company
+changeStatus(email, status)
}

class "Company" {
-profileContainer
-accountContainer
+getProfileContainer()
+getAccountContainer()
}

class "ProfileContainer"{
-profiles
+addProfile(profile)
+doesProfileNameExist(profileName)
+getProfileByName(profileName)
}

class "Profile"{
-profileName
+Profile(profileName)
+getProfileName(profileName)
}

class "AccountContainer"{
-accounts
+addAccount(account)
+doesEmailExist(email)
+getAccountByEmail(email)
+getAccounts()
}

class "Account" {
-name
-email
-phoneNumber
-photo
-status
-profile
+Account(name, email, phoneNumber, photo, status)
+getEmail(email)
+setProfile(profile)
+setStatus(status)
}

"CreateProfileController" ..>  "Company"
"CreateProfileController" ..> "ProfileContainer"
"CreateProfileController" ..> "Profile"
"Company" "1"-->"1" "ProfileContainer": has
"ProfileContainer" "1" --> "*" "Profile": contains

"RegisterAccountController" ..>  "Company"
"RegisterAccountController" ..> "Account"
"RegisterAccountController" ..> "AccountContainer"
"Company" "1"-->"1" "AccountContainer": has
"AccountContainer" "1"-->"*" "Account": contains

ChangeProfileController ..> Company
ChangeProfileController ..> ProfileContainer
ChangeProfileController ..> AccountContainer
ChangeProfileController ..> Account

"ListAccountController" ..> "Company"
"ListAccountController" ..> "AccountContainer"

"ChangeStatusController" ..> "Company"
"ChangeStatusController" ..> "AccountContainer"
"ChangeStatusController" ..> "Account"

@enduml