@startuml

skinparam sequenceMessageAlign center
actor "Administrator"
participant ":CreateAccountListController" as cal
participant ":Account" as acc
participant "AccountList" as acclist

activate Administrator
Administrator -> cal: 1 request list of all accounts and status
activate cal
cal -> acc: 1.1 accountInfo=createInfo(e-mail, status)
activate acc
acc -> acclist: 1.1.1 getEmailStatus()
activate acclist
deactivate acc
acclist -> acclist: 1.1.1.1 addToList(accountInfo)
cal --> Administrator: returns data
deactivate acclist

@enduml